//! Generated by tools/gen_anim_tests.py from DevilutionX 1.5.3's test/animationinfo_test.cpp.
//! Simulates game ticks and renders between them; the animation distribution logic must pick the
//! same frame as the original at every step. Do not edit by hand.

use diablo1_rs::engine::animationinfo::AnimationInfo;
use diablo1_rs::enums::AnimationDistributionFlags as F;

enum Step {
    /// `SetNewAnimationData(numberOfFrames, delayLen, params, numSkippedFrames, distributeFramesBeforeFrame)`
    New(i8, i8, F, i8, i8),
    /// `GameTickData(expectedAnimationFrame, expectedAnimationCnt)`
    Tick(i8, i8),
    /// `RenderingData(fProgressToNextGameTick, expectedRenderingFrame)`
    Render(f32, i8),
}
use Step::*;

/// `RunAnimationTest`
fn run_animation_test(steps: &[Step]) {
    let mut anim = AnimationInfo::default();
    let mut current_game_tick = 0;
    for step in steps {
        match *step {
            New(frames, delay, flags, skipped, before) => anim.set_new_animation(None, frames, delay, flags, skipped, before, 0),
            Tick(frame, cnt) => {
                current_game_tick += 1;
                anim.process_animation(false);
                assert_eq!((anim.currentFrame, anim.tickCounterOfCurrentFrame), (frame, cnt), "GameTick: {current_game_tick}");
            }
            Render(progress, frame) => {
                let progress_to_next_game_tick = (progress * AnimationInfo::BASE_VALUE_FRACTION as f32) as u8;
                assert_eq!(
                    anim.get_frame_to_use_for_rendering(progress_to_next_game_tick),
                    frame,
                    "ProgressToNextGameTick: {progress:.2} currentFrame: {} DelayCounter: {} GameTick: {current_game_tick}",
                    anim.currentFrame,
                    anim.tickCounterOfCurrentFrame
                );
            }
        }
    }
}


/// ProcessAnimationPending should be considered by distribution logic
#[test]
fn attack_sword_warrior() {
    run_animation_test(&[
        // ProcessAnimationPending should be considered by distribution logic
        New(16, 1, F(F::ProcessAnimationPending.0), 0, 9),
        // processAnimation directly after StartAttack (in same GameTick). So we don't see any rendering before.
        Tick(1, 0),
        Render(0.0, 0),
        Render(0.3, 0),
        Render(0.6, 0),
        Render(0.8, 0),
        Tick(2, 0),
        Render(0.0, 1),
        Render(0.3, 1),
        Render(0.6, 1),
        Render(0.8, 2),
        Tick(3, 0),
        Render(0.0, 2),
        Render(0.3, 2),
        Render(0.6, 2),
        Render(0.8, 3),
        Tick(4, 0),
        Render(0.0, 3),
        Render(0.3, 3),
        Render(0.6, 4),
        Render(0.8, 4),
        Tick(5, 0),
        Render(0.0, 4),
        Render(0.3, 4),
        Render(0.6, 5),
        Render(0.8, 5),
        Tick(6, 0),
        Render(0.0, 5),
        Render(0.3, 6),
        Render(0.6, 6),
        Render(0.8, 6),
        Tick(7, 0),
        Render(0.0, 6),
        Render(0.3, 7),
        Render(0.6, 7),
        Render(0.8, 7),
        // After this GameTick, the Animation Distribution Logic is disabled
        Tick(8, 0),
        Render(0.1, 8),
        Tick(9, 0),
        Render(0.4, 9),
        Tick(10, 0),
        Render(0.4, 10),
        Tick(11, 0),
        Render(0.3, 11),
        Tick(12, 0),
        Render(0.0, 12),
        Tick(13, 0),
        Render(0.6, 13),
        Tick(14, 0),
        Render(0.6, 14),
        Tick(15, 0),
        Render(0.6, 15),
        // Animation stopped cause PM_DoAttack would stop the Animation "if (plr[pnum].AnimInfo.currentFrame == plr[pnum]._pAFrames - 1) {"
    ]);
}

/// Skipped frames and ProcessAnimationPending should be considered by distribution logic
#[test]
fn attack_sword_warrior_with_fastest_attack() {
    run_animation_test(&[
        // Skipped frames and ProcessAnimationPending should be considered by distribution logic
        New(16, 1, F(F::ProcessAnimationPending.0), 2, 9),
        // processAnimation directly after StartAttack (in same GameTick). So we don't see any rendering before.
        Tick(3, 0),
        Render(0.0, 0),
        Render(0.3, 0),
        Render(0.6, 0),
        Render(0.8, 1),
        Tick(4, 0),
        Render(0.0, 1),
        Render(0.3, 2),
        Render(0.6, 2),
        Render(0.8, 2),
        Tick(5, 0),
        Render(0.0, 3),
        Render(0.3, 3),
        Render(0.6, 4),
        Render(0.8, 4),
        Tick(6, 0),
        Render(0.0, 4),
        Render(0.3, 5),
        Render(0.6, 5),
        Render(0.8, 6),
        Tick(7, 0),
        Render(0.0, 6),
        Render(0.3, 6),
        Render(0.6, 7),
        Render(0.8, 7),
        // After this GameTick, the Animation Distribution Logic is disabled
        Tick(8, 0),
        Render(0.1, 8),
        Tick(9, 0),
        Render(0.4, 9),
        Tick(10, 0),
        Render(0.4, 10),
        Tick(11, 0),
        Render(0.3, 11),
        Tick(12, 0),
        Render(0.0, 12),
        Tick(13, 0),
        Render(0.6, 13),
        Tick(14, 0),
        Render(0.6, 14),
        Tick(15, 0),
        Render(0.6, 15),
        // Animation stopped cause PM_DoAttack would stop the Animation "if (plr[pnum].AnimInfo.currentFrame == plr[pnum]._pAFrames - 1) {"
    ]);
}

#[test]
fn attack_sword_warrior_repeated() {
    run_animation_test(&[
        New(16, 1, F(F::ProcessAnimationPending.0), 0, 9),
        // processAnimation directly after StartAttack (in same GameTick). So we don't see any rendering before.
        Tick(1, 0),
        Render(0.0, 0),
        Render(0.3, 0),
        Render(0.6, 0),
        Render(0.8, 0),
        Tick(2, 0),
        Render(0.0, 1),
        Render(0.3, 1),
        Render(0.6, 1),
        Render(0.8, 2),
        Tick(3, 0),
        Render(0.0, 2),
        Render(0.3, 2),
        Render(0.6, 2),
        Render(0.8, 3),
        Tick(4, 0),
        Render(0.0, 3),
        Render(0.3, 3),
        Render(0.6, 4),
        Render(0.8, 4),
        Tick(5, 0),
        Render(0.0, 4),
        Render(0.3, 4),
        Render(0.6, 5),
        Render(0.8, 5),
        Tick(6, 0),
        Render(0.0, 5),
        Render(0.3, 6),
        Render(0.6, 6),
        Render(0.8, 6),
        Tick(7, 0),
        Render(0.0, 6),
        Render(0.3, 7),
        Render(0.6, 7),
        Render(0.8, 7),
        // After this GameTick, the Animation Distribution Logic is disabled
        Tick(8, 0),
        Render(0.1, 8),
        Tick(9, 0),
        Render(0.3, 9),
        // Start of repeated attack, cause plr[pnum].AnimInfo.currentFrame > plr[myplr]._pAFNum
        New(16, 1, F(F::ProcessAnimationPending.0 | F::RepeatedAction.0), 0, 9),
        // processAnimation directly after StartAttack (in same GameTick). So we don't see any rendering before.
        Tick(1, 0),
        Render(0.0, 10),
        Render(0.3, 10),
        Render(0.6, 11),
        Render(0.8, 11),
        Tick(2, 0),
        Render(0.0, 12),
        Render(0.3, 12),
        Render(0.6, 13),
        Render(0.8, 13),
        Tick(3, 0),
        Render(0.0, 14),
        Render(0.3, 14),
        Render(0.6, 15),
        Render(0.8, 15),
        Tick(4, 0),
        Render(0.0, 0),
        Render(0.3, 0),
        Render(0.6, 1),
        Render(0.8, 1),
        Tick(5, 0),
        Render(0.0, 2),
        Render(0.3, 2),
        Render(0.6, 3),
        Render(0.8, 3),
        Tick(6, 0),
        Render(0.0, 4),
        Render(0.3, 4),
        Render(0.6, 5),
        Render(0.8, 5),
        Tick(7, 0),
        Render(0.0, 6),
        Render(0.3, 6),
        Render(0.6, 7),
        Render(0.8, 7),
        // After this GameTick, the Animation Distribution Logic is disabled
        Tick(8, 0),
        Render(0.1, 8),
        Tick(9, 0),
        Render(0.4, 9),
        Tick(10, 0),
        Render(0.4, 10),
        Tick(11, 0),
        Render(0.3, 11),
        Tick(12, 0),
        Render(0.0, 12),
        Tick(13, 0),
        Render(0.6, 13),
        Tick(14, 0),
        Render(0.6, 14),
        Tick(15, 0),
        Render(0.6, 15),
        // Animation stopped cause PM_DoAttack would stop the Animation "if (plr[pnum].AnimInfo.currentFrame == plr[pnum]._pAFrames - 1) {"
    ]);
}

/// Ignored delay for last Frame should be considered by distribution logic
#[test]
fn blocking_warrior_normal() {
    run_animation_test(&[
        // Ignored delay for last Frame should be considered by distribution logic
        New(2, 3, F(F::SkipsDelayOfLastFrame.0), 0, 0),
        Render(0.0, 0),
        Render(0.3, 0),
        Render(0.6, 0),
        Render(0.8, 0),
        Tick(0, 1),
        Render(0.0, 0),
        Render(0.3, 0),
        Render(0.6, 0),
        Render(0.8, 0),
        Tick(0, 2),
        Render(0.0, 1),
        Render(0.3, 1),
        Render(0.6, 1),
        Render(0.8, 1),
        Tick(1, 0),
        Render(0.0, 1),
        Render(0.3, 1),
        Render(0.6, 1),
        Render(0.8, 1),
        // Animation stopped cause PM_DoBlock would stop the Animation "if (plr[pnum].AnimInfo.currentFrame >= plr[pnum]._pBFrames) {"
    ]);
}

/// Skipped frames and ignored delay for last Frame should be considered by distribution logic
#[test]
fn blocking_sorcerer_with_fast_block() {
    run_animation_test(&[
        // Skipped frames and ignored delay for last Frame should be considered by distribution logic
        New(6, 3, F(F::SkipsDelayOfLastFrame.0), 4, 0),
        Render(0.0, 0),
        Render(0.3, 0),
        Render(0.6, 0),
        Render(0.8, 1),
        Tick(4, 1),
        Render(0.0, 1),
        Render(0.3, 1),
        Render(0.6, 2),
        Render(0.8, 2),
        Tick(4, 2),
        Render(0.0, 3),
        Render(0.3, 3),
        Render(0.6, 3),
        Render(0.8, 4),
        Tick(5, 0),
        Render(0.0, 4),
        Render(0.3, 4),
        Render(0.6, 5),
        Render(0.8, 5),
        // Animation stopped cause PM_DoBlock would stop the Animation "if (plr[pnum].AnimInfo.currentFrame >= plr[pnum]._pBFrames) {"
    ]);
}

/// Skipped frames and ignored delay for last Frame should be considered by distribution logic
#[test]
fn hit_recovery_sorcerer_harmony() {
    run_animation_test(&[
        // Skipped frames and ignored delay for last Frame should be considered by distribution logic
        New(8, 1, F(F::None.0), 3, 0),
        Render(0.0, 0),
        Render(0.3, 0),
        Render(0.6, 0),
        Render(0.8, 1),
        Tick(4, 0),
        Render(0.0, 1),
        Render(0.3, 2),
        Render(0.6, 2),
        Render(0.8, 2),
        Tick(5, 0),
        Render(0.0, 3),
        Render(0.3, 3),
        Render(0.6, 4),
        Render(0.8, 4),
        Tick(6, 0),
        Render(0.0, 4),
        Render(0.3, 5),
        Render(0.6, 5),
        Render(0.8, 6),
        Tick(7, 0),
        Render(0.0, 6),
        Render(0.3, 6),
        Render(0.6, 7),
        Render(0.8, 7),
        // Animation stopped cause PM_DoGotHit would stop the Animation "if (plr[pnum].AnimInfo.currentFrame >= plr[pnum]._pHFrames) {"
    ]);
}

/// Distribution Logic shouldn't change anything here
#[test]
fn stand() {
    run_animation_test(&[
        // Distribution Logic shouldn't change anything here
        New(10, 4, F::None, 0, 0),
        Render(0.1, 0),
        Tick(0, 1),
        Render(0.6, 0),
        Tick(0, 2),
        Render(0.6, 0),
        Tick(0, 3),
        Render(0.6, 0),
        Tick(1, 0),
        Render(0.6, 1),
        Tick(1, 1),
        Render(0.6, 1),
        Tick(1, 2),
        Render(0.6, 1),
        Tick(1, 3),
        Render(0.6, 1),
        Tick(2, 0),
        Render(0.6, 2),
        Tick(2, 1),
        Render(0.6, 2),
        Tick(2, 2),
        Render(0.6, 2),
        Tick(2, 3),
        Render(0.6, 2),
        Tick(3, 0),
        Render(0.6, 3),
        Tick(3, 1),
        Render(0.6, 3),
        Tick(3, 2),
        Render(0.6, 3),
        Tick(3, 3),
        Render(0.6, 3),
        Tick(4, 0),
        Render(0.6, 4),
        Tick(4, 1),
        Render(0.6, 4),
        Tick(4, 2),
        Render(0.6, 4),
        Tick(4, 3),
        Render(0.6, 4),
        Tick(5, 0),
        Render(0.6, 5),
        Tick(5, 1),
        Render(0.6, 5),
        Tick(5, 2),
        Render(0.6, 5),
        Tick(5, 3),
        Render(0.6, 5),
        Tick(6, 0),
        Render(0.6, 6),
        Tick(6, 1),
        Render(0.6, 6),
        Tick(6, 2),
        Render(0.6, 6),
        Tick(6, 3),
        Render(0.6, 6),
        Tick(7, 0),
        Render(0.6, 7),
        Tick(7, 1),
        Render(0.6, 7),
        Tick(7, 2),
        Render(0.6, 7),
        Tick(7, 3),
        Render(0.6, 7),
        Tick(8, 0),
        Render(0.6, 8),
        Tick(8, 1),
        Render(0.6, 8),
        Tick(8, 2),
        Render(0.6, 8),
        Tick(8, 3),
        Render(0.6, 8),
        Tick(9, 0),
        Render(0.6, 9),
        Tick(9, 1),
        Render(0.6, 9),
        Tick(9, 2),
        Render(0.6, 9),
        Tick(9, 3),
        Render(0.6, 9),
        // Animation starts again
        Tick(0, 0),
        Render(0.1, 0),
        Tick(0, 1),
        Render(0.6, 0),
        Tick(0, 2),
        Render(0.6, 0),
        Tick(0, 3),
        Render(0.6, 0),
    ]);
}
