//! Generated by `tools/gen_drlg_tests.py` from DevilutionX 1.5.3's test/drlg_l*_test.cpp. Do not edit.
//!
//! Dungeon generation parity: every tile and room index of the generated level must match the
//! level DevilutionX generated for the same seed (test/fixtures/*.dun in the DevilutionX source).

#![allow(non_snake_case)]

mod common;

use common::drlg::Harness;
use diablo1_rs::engine::geometry::Point;
use diablo1_rs::enums::*;

#[test]
fn drlg_l1_create_l5_dungeon_diablo_1_2588() {
    let Some(mut t) = Harness::new("diablo/1-2588.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(1, 2588, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(77, 46));
    t.create_dungeon(1, 2588, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(49, 49));
}

#[test]
fn drlg_l1_create_l5_dungeon_diablo_1_743271966() {
    let Some(mut t) = Harness::new("diablo/1-743271966.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(1, 743271966, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(51, 82));
    t.create_dungeon(1, 743271966, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(81, 47));
}

#[test]
fn drlg_l1_create_l5_dungeon_diablo_2_1383137027() {
    let Some(mut t) = Harness::new("diablo/2-1383137027.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_PWATER as usize]._qactive = QUEST_INIT;
    t.ctx.quests.Quests[Q_BUTCHER as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(2, 1383137027, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(57, 74));
    t.create_dungeon(2, 1383137027, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(57, 79));
    t.create_dungeon(2, 1383137027, ENTRY_RTNLVL);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(49, 88));
}

#[test]
fn drlg_l1_create_l5_dungeon_diablo_3_844660068() {
    let Some(mut t) = Harness::new("diablo/3-844660068.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(3, 844660068, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(67, 52));
    t.create_dungeon(3, 844660068, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(85, 45));
}

#[test]
fn drlg_l1_create_l5_dungeon_diablo_4_609325643() {
    let Some(mut t) = Harness::new("diablo/4-609325643.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_LTBANNER as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(4, 609325643, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(85, 78));
    t.create_dungeon(4, 609325643, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(55, 47));
}

#[test]
fn drlg_l1_create_l5_dungeon_diablo_4_902156014() {
    let Some(mut t) = Harness::new("diablo/4-902156014.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_LTBANNER as usize]._qactive = QUEST_INIT;
    t.create_dungeon(4, 902156014, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(75, 56));
    t.create_dungeon(4, 902156014, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(51, 59));
}

#[test]
fn drlg_l1_create_l5_dungeon_hellfire_1_401921334() {
    let Some(mut t) = Harness::new("hellfire/1-401921334.dun") else { return };
    t.init_game(true, false);
    t.create_dungeon(1, 401921334, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(79, 80));
    t.create_dungeon(1, 401921334, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(49, 63));
}

#[test]
fn drlg_l1_create_l5_dungeon_hellfire_1_536340718() {
    let Some(mut t) = Harness::new("hellfire/1-536340718.dun") else { return };
    t.init_game(true, false);
    t.create_dungeon(1, 536340718, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(55, 72));
    t.create_dungeon(1, 536340718, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(49, 63));
}

#[test]
fn drlg_l1_create_l5_dungeon_hellfire_2_128964898() {
    let Some(mut t) = Harness::new("hellfire/2-128964898.dun") else { return };
    t.init_game(true, false);
    t.ctx.quests.Quests[Q_PWATER as usize]._qactive = QUEST_NOTAVAIL;
    t.ctx.quests.Quests[Q_BUTCHER as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(2, 128964898, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(55, 68));
    t.create_dungeon(2, 128964898, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(49, 63));
}

#[test]
fn drlg_l1_create_l5_dungeon_hellfire_2_1180526547() {
    let Some(mut t) = Harness::new("hellfire/2-1180526547.dun") else { return };
    t.init_game(true, false);
    t.ctx.quests.Quests[Q_PWATER as usize]._qactive = QUEST_NOTAVAIL;
    t.ctx.quests.Quests[Q_BUTCHER as usize]._qactive = QUEST_INIT;
    t.create_dungeon(2, 1180526547, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(83, 68));
    t.create_dungeon(2, 1180526547, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(81, 45));
}

#[test]
fn drlg_l1_create_l5_dungeon_hellfire_3_1369955278() {
    let Some(mut t) = Harness::new("hellfire/3-1369955278.dun") else { return };
    t.init_game(true, false);
    t.ctx.quests.Quests[Q_SKELKING as usize]._qactive = QUEST_INIT;
    t.create_dungeon(3, 1369955278, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(63, 86));
    t.create_dungeon(3, 1369955278, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(75, 69));
}

#[test]
fn drlg_l1_create_l5_dungeon_hellfire_3_1799396623() {
    let Some(mut t) = Harness::new("hellfire/3-1799396623.dun") else { return };
    t.init_game(true, false);
    t.ctx.quests.Quests[Q_SKELKING as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(3, 1799396623, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(59, 68));
    t.create_dungeon(3, 1799396623, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(47, 55));
}

#[test]
fn drlg_l1_create_l5_dungeon_hellfire_3_1512491184() {
    let Some(mut t) = Harness::new("hellfire/3-1512491184.dun") else { return };
    t.init_game(true, false);
    t.ctx.quests.Quests[Q_SKELKING as usize]._qactive = QUEST_INIT;
    t.create_dungeon(3, 1512491184, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(47, 72));
    t.create_dungeon(3, 1512491184, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(79, 45));
}

#[test]
fn drlg_l1_create_l5_dungeon_hellfire_4_1190318991() {
    let Some(mut t) = Harness::new("hellfire/4-1190318991.dun") else { return };
    t.init_game(true, false);
    t.ctx.quests.Quests[Q_LTBANNER as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(4, 1190318991, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(67, 80));
    t.create_dungeon(4, 1190318991, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(77, 45));
}

#[test]
fn drlg_l1_create_l5_dungeon_hellfire_4_1924296259() {
    let Some(mut t) = Harness::new("hellfire/4-1924296259.dun") else { return };
    t.init_game(true, false);
    t.ctx.quests.Quests[Q_LTBANNER as usize]._qactive = QUEST_INIT;
    t.create_dungeon(4, 1924296259, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(83, 54));
    t.create_dungeon(4, 1924296259, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(51, 87));
}

#[test]
fn drlg_l1_create_l5_dungeon_crypt_1_2122696790() {
    let Some(mut t) = Harness::new("hellfire/21-2122696790.dun") else { return };
    if !t.use_source_assets() {
        return;
    }
    t.init_game(true, true);
    t.create_dungeon(21, 2122696790, ENTRY_TWARPDN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(61, 81));
    t.create_dungeon(21, 2122696790, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(53, 67));
}

#[test]
fn drlg_l1_create_l5_dungeon_crypt_2_1191662129() {
    let Some(mut t) = Harness::new("hellfire/22-1191662129.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_PWATER as usize]._qactive = QUEST_NOTAVAIL;
    t.ctx.quests.Quests[Q_BUTCHER as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(22, 1191662129, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(71, 47));
    t.create_dungeon(22, 1191662129, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(85, 71));
}

#[test]
fn drlg_l1_create_l5_dungeon_crypt_3_97055268() {
    let Some(mut t) = Harness::new("hellfire/23-97055268.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(23, 97055268, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(71, 57));
    t.create_dungeon(23, 97055268, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(81, 59));
}

#[test]
fn drlg_l1_create_l5_dungeon_crypt_4_1324803725() {
    let Some(mut t) = Harness::new("hellfire/24-1324803725.dun") else { return };
    if !t.use_source_assets() {
        return;
    }
    t.init_game(true, true);
    t.create_dungeon(24, 1324803725, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(79, 47));
}

#[test]
fn drlg_l2_create_l2_dungeon_diablo_5_1677631846() {
    let Some(mut t) = Harness::new("diablo/5-1677631846.dun") else { return };
    diablo1_rs::quests::init_quests(&mut t.ctx);
    t.ctx.quests.Quests[Q_BLOOD as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(5, 1677631846, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(27, 28));
    t.create_dungeon(5, 1677631846, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(26, 62));
    t.create_dungeon(5, 1677631846, ENTRY_TWARPDN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(33, 56));
}

#[test]
fn drlg_l2_create_l2_dungeon_diablo_5_68685319() {
    let Some(mut t) = Harness::new("diablo/5-68685319.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_BLOOD as usize]._qactive = QUEST_INIT;
    t.create_dungeon(5, 68685319, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(37, 36));
    t.create_dungeon(5, 68685319, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(44, 28));
    t.create_dungeon(5, 68685319, ENTRY_TWARPDN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(45, 76));
}

#[test]
fn drlg_l2_create_l2_dungeon_diablo_6_2034738122() {
    let Some(mut t) = Harness::new("diablo/6-2034738122.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_SCHAMB as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(6, 2034738122, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(33, 26));
    t.create_dungeon(6, 2034738122, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(34, 52));
}

#[test]
fn drlg_l2_create_l2_dungeon_diablo_6_1824554527() {
    let Some(mut t) = Harness::new("diablo/6-1824554527.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_SCHAMB as usize]._qactive = QUEST_INIT;
    t.create_dungeon(6, 1824554527, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(35, 36));
    t.create_dungeon(6, 1824554527, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(28, 76));
}

#[test]
fn drlg_l2_create_l2_dungeon_diablo_6_2033265779() {
    let Some(mut t) = Harness::new("diablo/6-2033265779.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_SCHAMB as usize]._qactive = QUEST_INIT;
    t.create_dungeon(6, 2033265779, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(27, 28));
    t.create_dungeon(6, 2033265779, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(64, 64));
}

#[test]
fn drlg_l2_create_l2_dungeon_diablo_7_680552750() {
    let Some(mut t) = Harness::new("diablo/7-680552750.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_BLIND as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(7, 680552750, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(27, 26));
    t.create_dungeon(7, 680552750, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(78, 52));
}

#[test]
fn drlg_l2_create_l2_dungeon_diablo_7_1607627156() {
    let Some(mut t) = Harness::new("diablo/7-1607627156.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_BLIND as usize]._qactive = QUEST_INIT;
    t.create_dungeon(7, 1607627156, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(53, 26));
    t.create_dungeon(7, 1607627156, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(50, 88));
}

#[test]
fn drlg_l2_create_l2_dungeon_diablo_8_1999936419() {
    let Some(mut t) = Harness::new("diablo/8-1999936419.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(8, 1999936419, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(39, 74));
    t.create_dungeon(8, 1999936419, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(48, 46));
}

#[test]
fn drlg_l3_create_l3_dungeon_diablo_9_262005438() {
    let Some(mut t) = Harness::new("diablo/9-262005438.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(9, 262005438, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(41, 73));
    t.create_dungeon(9, 262005438, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(73, 59));
    t.create_dungeon(9, 262005438, ENTRY_TWARPDN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(37, 35));
}

#[test]
fn drlg_l3_create_l3_dungeon_diablo_10_1630062353() {
    let Some(mut t) = Harness::new("diablo/10-1630062353.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_ANVIL as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(10, 1630062353, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(55, 37));
    t.create_dungeon(10, 1630062353, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(19, 47));
}

#[test]
fn drlg_l3_create_l3_dungeon_diablo_10_879635115() {
    let Some(mut t) = Harness::new("diablo/10-879635115.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_ANVIL as usize]._qlevel = 10;
    t.ctx.quests.Quests[Q_ANVIL as usize]._qactive = QUEST_INIT;
    t.create_dungeon(10, 879635115, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(75, 41));
    t.create_dungeon(10, 879635115, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(27, 45));
}

#[test]
fn drlg_l3_create_l3_dungeon_diablo_11_384626536() {
    let Some(mut t) = Harness::new("diablo/11-384626536.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(11, 384626536, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(29, 19));
    t.create_dungeon(11, 384626536, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(65, 65));
}

#[test]
fn drlg_l3_create_l3_dungeon_diablo_12_2104541047() {
    let Some(mut t) = Harness::new("diablo/12-2104541047.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(12, 2104541047, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(35, 23));
    t.create_dungeon(12, 2104541047, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(21, 83));
}

#[test]
fn drlg_l3_create_l3_dungeon_hive_1_19770182() {
    let Some(mut t) = Harness::new("hellfire/17-19770182.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(17, 19770182, ENTRY_TWARPDN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(75, 81));
    t.create_dungeon(17, 19770182, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(59, 41));
}

#[test]
fn drlg_l3_create_l3_dungeon_hive_2_1522546307() {
    let Some(mut t) = Harness::new("hellfire/18-1522546307.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(18, 1522546307, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(47, 19));
    t.create_dungeon(18, 1522546307, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(33, 35));
}

#[test]
fn drlg_l3_create_l3_dungeon_hive_3_125121312() {
    let Some(mut t) = Harness::new("hellfire/19-125121312.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(19, 125121312, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(61, 25));
    t.create_dungeon(19, 125121312, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(21, 85));
}

#[test]
fn drlg_l3_create_l3_dungeon_hive_4_1511478689() {
    let Some(mut t) = Harness::new("hellfire/20-1511478689.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(20, 1511478689, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(65, 41));
}

#[test]
fn drlg_l4_create_l4_dungeon_diablo_13_428074402() {
    let Some(mut t) = Harness::new("diablo/13-428074402.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_WARLORD as usize]._qactive = QUEST_NOTAVAIL;
    t.create_dungeon(13, 428074402, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(26, 64));
    t.create_dungeon(13, 428074402, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(49, 77));
    t.create_dungeon(13, 428074402, ENTRY_TWARPDN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(26, 44));
}

#[test]
fn drlg_l4_create_l4_dungeon_diablo_13_594689775() {
    let Some(mut t) = Harness::new("diablo/13-594689775.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_WARLORD as usize]._qactive = QUEST_INIT;
    t.create_dungeon(13, 594689775, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(72, 38));
    t.create_dungeon(13, 594689775, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(33, 41));
    t.create_dungeon(13, 594689775, ENTRY_TWARPDN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(36, 88));
}

#[test]
fn drlg_l4_create_l4_dungeon_diablo_14_717625719() {
    let Some(mut t) = Harness::new("diablo/14-717625719.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(14, 717625719, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(90, 64));
    t.create_dungeon(14, 717625719, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(51, 29));
}

#[test]
fn drlg_l4_create_l4_dungeon_diablo_14_815743776() {
    let Some(mut t) = Harness::new("diablo/14-815743776.dun") else { return };
    t.init_game(true, true);
    t.create_dungeon(14, 815743776, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(66, 60));
    t.create_dungeon(14, 815743776, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(27, 75));
}

#[test]
fn drlg_l4_create_l4_dungeon_diablo_15_1583642716() {
    let Some(mut t) = Harness::new("diablo/15-1583642716.dun") else { return };
    t.init_game(true, true);
    t.ctx.quests.Quests[Q_DIABLO as usize]._qactive = QUEST_INIT;
    t.create_dungeon(15, 1583642716, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(44, 26));
    t.create_dungeon(15, 1583642716, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(88, 67));
    t.ctx.quests.Quests[Q_BETRAYER as usize]._qactive = QUEST_ACTIVE;
    t.create_dungeon(15, 1583642716, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(44, 26));
    assert_eq!(t.ctx.quests.Quests[Q_BETRAYER as usize].position, Point::new(84, 64), "Ensure the portal to lazarus has a spawn position if the player has activated the quest");
    if !t.load_expected("diablo/15-1583642716-changed.dun") {
        return;
    }
    t.ctx.quests.Quests[Q_BETRAYER as usize]._qactive = QUEST_DONE;
    t.ctx.quests.Quests[Q_DIABLO as usize]._qactive = QUEST_ACTIVE;
    t.create_dungeon(15, 1583642716, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(44, 26));
    assert_eq!(t.ctx.quests.Quests[Q_BETRAYER as usize].position, Point::new(84, 64), "Not really required? current bugfix sets this position anyway");
    t.create_dungeon(15, 1583642716, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(88, 67));
    assert_eq!(t.ctx.quests.Quests[Q_BETRAYER as usize].position, Point::new(84, 64), "Not really required? current bugfix sets this position anyway");
}

#[test]
fn drlg_l4_create_l4_dungeon_diablo_15_1256511996() {
    let Some(mut t) = Harness::new("diablo/15-1256511996.dun") else { return };
    t.init_game(false, true);
    t.create_dungeon(15, 1256511996, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(80, 70));
    t.create_dungeon(15, 1256511996, ENTRY_PREV);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(34, 65));
}

#[test]
fn drlg_l4_create_l4_dungeon_diablo_16_741281013() {
    let Some(mut t) = Harness::new("diablo/16-741281013.dun") else { return };
    t.create_dungeon(16, 741281013, ENTRY_MAIN);
    assert_eq!(t.ctx.gendung.ViewPosition, Point::new(58, 42));
}
