//! Parity between the port and the reference database (via port/db_functions.csv, generated by
//! tools/gen_manifest.py from portdb/diablo1.sqlite).

use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Minimal RFC 4180 reader: quoted fields, doubled quotes, commas and newlines inside quotes.
fn read_csv(path: &Path) -> Vec<HashMap<String, String>> {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let mut records: Vec<Vec<String>> = Vec::new();
    let (mut rec, mut field, mut quoted) = (Vec::new(), String::new(), false);
    let mut chars = text.chars().peekable();
    while let Some(c) = chars.next() {
        match (c, quoted) {
            ('"', true) if chars.peek() == Some(&'"') => {
                field.push('"');
                chars.next();
            }
            ('"', _) => quoted = !quoted,
            (',', false) => rec.push(std::mem::take(&mut field)),
            ('\r', false) => {}
            ('\n', false) => {
                rec.push(std::mem::take(&mut field));
                records.push(std::mem::take(&mut rec));
            }
            _ => field.push(c),
        }
    }
    if !field.is_empty() || !rec.is_empty() {
        rec.push(field);
        records.push(rec);
    }
    let header = records.remove(0);
    records
        .into_iter()
        .map(|r| header.iter().cloned().zip(r).collect())
        .collect()
}

struct Tag {
    key: String,
    sha: String,
    file: PathBuf,
    line: usize,
}

fn tags() -> Vec<Tag> {
    let mut out = Vec::new();
    let mut stack = vec![root().join("src")];
    while let Some(dir) = stack.pop() {
        for e in fs::read_dir(&dir).unwrap() {
            let p = e.unwrap().path();
            if p.is_dir() {
                stack.push(p);
            } else if p.extension().is_some_and(|x| x == "rs") {
                for (i, line) in fs::read_to_string(&p).unwrap().lines().enumerate() {
                    if let Some(rest) = line.trim_start().strip_prefix("// @port ") {
                        let (key, sha) = rest.rsplit_once(" sha=").unwrap_or((rest, ""));
                        out.push(Tag { key: key.to_string(), sha: sha.trim().to_string(), file: p.clone(), line: i + 1 });
                    }
                }
            }
        }
    }
    out
}

#[test]
fn manifest_accounts_for_every_database_function() {
    let db = read_csv(&root().join("port/db_functions.csv"));
    let manifest = read_csv(&root().join("port/manifest.csv"));
    let keys: HashSet<&str> = manifest.iter().map(|r| r["key"].as_str()).collect();
    assert_eq!(keys.len(), manifest.len(), "duplicate keys in manifest.csv");
    let missing: Vec<&str> = db.iter().map(|r| r["key"].as_str()).filter(|k| !keys.contains(k)).collect();
    assert!(missing.is_empty(), "{} database functions missing from manifest, e.g. {:?}", missing.len(), &missing[..missing.len().min(5)]);
    let mut bad = Vec::new();
    for r in &manifest {
        match r["status"].as_str() {
            "ported" | "pending" => {}
            "replaced" if !r["replaced_by"].is_empty() && !r["reason"].is_empty() => {}
            s => bad.push(format!("{} -> {s}", r["key"])),
        }
    }
    assert!(bad.is_empty(), "invalid manifest rows (removed, or replaced without a reason): {bad:#?}");
}

#[test]
fn ported_functions_are_tagged_and_match_the_database() {
    let db: HashMap<String, HashMap<String, String>> =
        read_csv(&root().join("port/db_functions.csv")).into_iter().map(|r| (r["key"].clone(), r)).collect();
    let manifest = read_csv(&root().join("port/manifest.csv"));
    let ported: HashSet<&str> = manifest.iter().filter(|r| r["status"] == "ported").map(|r| r["key"].as_str()).collect();
    let tags = tags();
    let mut errors = Vec::new();
    let mut seen: HashMap<&str, usize> = HashMap::new();
    for t in &tags {
        *seen.entry(t.key.as_str()).or_default() += 1;
        let at = format!("{}:{}", t.file.display(), t.line);
        match db.get(&t.key) {
            None => errors.push(format!("{at}: tag names unknown function {}", t.key)),
            Some(r) if !r["sha256"].starts_with(&t.sha) || t.sha.len() < 12 => {
                errors.push(format!("{at}: {} source changed (db sha {}, tag sha {})", t.key, &r["sha256"][..12], t.sha))
            }
            _ => {}
        }
        if !ported.contains(t.key.as_str()) {
            errors.push(format!("{at}: {} is tagged but not marked ported in manifest.csv", t.key));
        }
    }
    for k in &ported {
        match seen.get(k) {
            None => errors.push(format!("{k}: marked ported but no `// @port` tag in src/")),
            Some(n) if *n > 1 => errors.push(format!("{k}: tagged {n} times")),
            _ => {}
        }
    }
    assert!(errors.is_empty(), "{} parity errors:\n{}", errors.len(), errors.join("\n"));
}
