//! Generated by `tools/gen_random_tests.py` from DevilutionX 1.5.3's test/random_test.cpp. Do not edit.

#![allow(unused_mut, clippy::identity_op, clippy::erasing_op)]

use diablo1_rs::engine::random::DiabloRng;

#[test]
fn random_engine_params() {
    let mut r = DiabloRng::default();
    let multiplicand: u32 = 22695477;
    let increment: u32 = 1;
    r.set_rnd_seed((0) as u32);
    assert_eq!(r.generate_seed(), increment);
    assert_eq!(r.generate_seed(), (multiplicand * 1) + increment);
    r.discard_random_values(9997);
    let mut expected_state = (3495122800) as u32;
    assert_eq!(r.generate_seed(), expected_state);
    expected_state = (3007658545) as u32;
    assert_eq!(r.generate_seed(), expected_state);
}

#[test]
fn abs_distribution() {
    let mut r = DiabloRng::default();
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.advance_rnd_seed(), i32::MIN);
    r.set_rnd_seed((3604671459) as u32);
    assert_eq!(r.advance_rnd_seed(), 0);
    r.set_rnd_seed((0) as u32);
    assert_eq!(r.advance_rnd_seed(), 1);
    r.set_rnd_seed((2914375622) as u32);
    assert_eq!(r.advance_rnd_seed(), 1);
    r.set_rnd_seed((3604671460) as u32);
    assert_eq!(r.advance_rnd_seed(), 22695477);
    r.set_rnd_seed((3604671458) as u32);
    assert_eq!(r.advance_rnd_seed(), 22695477);
    r.set_rnd_seed((1902003768) as u32);
    assert_eq!(r.advance_rnd_seed(), 429496729);
    r.set_rnd_seed((1012371854) as u32);
    assert_eq!(r.advance_rnd_seed(), 429496729);
    r.set_rnd_seed((189776845) as u32);
    assert_eq!(r.advance_rnd_seed(), 1212022642);
    r.set_rnd_seed((2724598777) as u32);
    assert_eq!(r.advance_rnd_seed(), 1212022642);
    r.set_rnd_seed((76596137) as u32);
    assert_eq!(r.advance_rnd_seed(), 2147483646);
    r.set_rnd_seed((2837779485) as u32);
    assert_eq!(r.advance_rnd_seed(), 2147483646);
    r.set_rnd_seed((766891974) as u32);
    assert_eq!(r.advance_rnd_seed(), 2147483647);
    r.set_rnd_seed((2147483648) as u32);
    assert_eq!(r.advance_rnd_seed(), 2147483647);
}

#[test]
fn mod_distribution_invalid_range() {
    let mut r = DiabloRng::default();
    let initial_seed = (44444444) as u32;
    r.set_rnd_seed((initial_seed) as u32);
    assert_eq!(r.generate_rnd(0), 0);
    assert_eq!(r.lcg_engine_state(), (initial_seed) as u32);
    assert_eq!(r.generate_rnd(-1), 0);
    assert_eq!(r.lcg_engine_state(), (initial_seed) as u32);
    assert_eq!(r.generate_rnd(i32::MIN), 0);
    assert_eq!(r.lcg_engine_state(), (initial_seed) as u32);
}

#[test]
fn shift_mod_distribution_single_range() {
    let mut r = DiabloRng::default();
    let initial_seed = (0x1234_5678) as u32;
    r.set_rnd_seed((initial_seed) as u32);
    for _i in 0..100 {
        assert_eq!(r.generate_rnd(1), 0);
    }
    assert_ne!(r.lcg_engine_state(), (initial_seed) as u32);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(1), 0);
}

#[test]
fn shift_mod_distribution_sign_carry() {
    let mut r = DiabloRng::default();
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(32767), -1);
}

#[test]
fn shift_mod_distribution_low_bits() {
    let mut r = DiabloRng::default();
    let max_bound = 32767;
    r.set_rnd_seed((3604671459) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((0) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((2914375622) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((538964771) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((2375410851) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((1229260608) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((1685115014) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((1768225379) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((1146150243) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((1480523688) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((1433851934) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((2382565573) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((531810049) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((1625910243) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((1288465379) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((2561524649) as u32);
    assert_eq!(r.generate_rnd(max_bound - 1), 0);
    r.set_rnd_seed((352850973) as u32);
    assert_eq!(r.generate_rnd(max_bound - 1), 0);
    r.set_rnd_seed((3251820486) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((3957522432) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
}

#[test]
fn shift_mod_distribution_high_bits() {
    let mut r = DiabloRng::default();
    let max_bound = 32767;
    r.set_rnd_seed((3267226595) as u32);
    assert_eq!(r.generate_rnd(max_bound), 1);
    r.set_rnd_seed((3942116323) as u32);
    assert_eq!(r.generate_rnd(max_bound), 1);
    r.set_rnd_seed((4279561187) as u32);
    assert_eq!(r.generate_rnd(max_bound), 2);
    r.set_rnd_seed((2929781731) as u32);
    assert_eq!(r.generate_rnd(max_bound), 2);
    r.set_rnd_seed((659483619) as u32);
    assert_eq!(r.generate_rnd(max_bound), 4);
    r.set_rnd_seed((2254892003) as u32);
    assert_eq!(r.generate_rnd(max_bound), 4);
    r.set_rnd_seed((3604671458) as u32);
    assert_eq!(r.generate_rnd(max_bound), 346);
    r.set_rnd_seed((3604671460) as u32);
    assert_eq!(r.generate_rnd(max_bound), 346);
    r.set_rnd_seed((1012371854) as u32);
    assert_eq!(r.generate_rnd(max_bound), 6553);
    r.set_rnd_seed((1902003768) as u32);
    assert_eq!(r.generate_rnd(max_bound), 6553);
    r.set_rnd_seed((189776845) as u32);
    assert_eq!(r.generate_rnd(max_bound), 18493);
    r.set_rnd_seed((2724598777) as u32);
    assert_eq!(r.generate_rnd(max_bound), 18493);
    r.set_rnd_seed((76596137) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((2837779485) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((766891974) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
    r.set_rnd_seed((2147483648) as u32);
    assert_eq!(r.generate_rnd(max_bound), 0);
}

#[test]
fn mod_distribution_sign_preserving() {
    let mut r = DiabloRng::default();
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(32768), 0);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(32769), -2);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(65535), -32768);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(i32::MAX), -1);
}

#[test]
fn negative_return_values() {
    let mut r = DiabloRng::default();
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(3), -2);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(5), -3);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(6), -2);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(7), -1);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(11), -10);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(17), -9);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(19), -12);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(22), -10);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(23), -16);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(25), -18);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(27), -17);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(29), -27);
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(31), -1);
    for i in [9, 10, 12, 13, 14, 15, 18, 20, 21, 24, 26, 28, 30] {
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(i), -8);
    }
    let mut i = 1;
    while i < 32768 {
    r.set_rnd_seed((1457187811) as u32);
    assert_eq!(r.generate_rnd(i), 0);
        i *= 2;
    }
}
