//! Generated by `tools/gen_tables.py` from `Source/items.cpp` (DevilutionX 1.5.3). Do not edit.

#![allow(non_snake_case, non_upper_case_globals, unused_imports, clippy::all)]

use crate::effects_data::*;
use crate::enums::*;

pub static ItemCAnimTbl: [i8; 229] = [20, 16, 16, 16, 4, 4, 4, 12, 12, 12, 12, 12, 12, 12, 12, 21, 21, 25, 12, 28, 28, 28, 38, 38, 38, 32, 38, 38, 38, 24, 24, 26, 2, 25, 22, 23, 24, 21, 27, 27, 29, 0, 0, 0, 12, 12, 12, 12, 12, 0, 8, 8, 0, 8, 8, 8, 8, 8, 8, 6, 8, 8, 8, 6, 8, 8, 6, 8, 8, 6, 6, 6, 8, 8, 8, 5, 9, 13, 13, 13, 5, 5, 5, 15, 5, 5, 18, 18, 18, 30, 5, 5, 14, 5, 14, 13, 16, 18, 5, 5, 7, 1, 3, 17, 1, 15, 10, 14, 3, 11, 8, 0, 1, 7, 0, 7, 15, 7, 3, 3, 3, 6, 6, 11, 11, 11, 31, 14, 14, 14, 6, 6, 7, 3, 8, 14, 0, 14, 14, 0, 33, 1, 1, 1, 1, 1, 7, 7, 7, 14, 14, 17, 17, 17, 0, 34, 1, 0, 3, 17, 8, 8, 6, 1, 3, 3, 11, 3, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 35, 39, 36, 36, 36, 37, 38, 38, 38, 38, 38, 41, 42, 8, 8, 8, 17, 0, 6, 8, 11, 11, 3, 3, 1, 6, 6, 6, 1, 8, 6, 11, 3, 6, 8, 1, 6, 6, 17, 40, 0, 0];

pub static ItemInvSnds: [SfxId; 43] = [IS_IHARM, IS_IAXE, IS_IPOT, IS_IBOW, IS_GOLD, IS_ICAP, IS_ISWORD, IS_ISHIEL, IS_ISWORD, IS_IROCK, IS_IAXE, IS_ISTAF, IS_IRING, IS_ICAP, IS_ILARM, IS_ISHIEL, IS_ISCROL, IS_IHARM, IS_IBOOK, IS_IHARM, IS_IPOT, IS_IPOT, IS_IPOT, IS_IPOT, IS_IPOT, IS_IPOT, IS_IPOT, IS_IPOT, IS_IBODY, IS_IBODY, IS_IMUSH, IS_ISIGN, IS_IBLST, IS_IANVL, IS_ISTAF, IS_IROCK, IS_ISCROL, IS_ISCROL, IS_IROCK, IS_IMUSH, IS_IHARM, IS_ILARM, IS_ILARM];

pub static OilLevels: [i32; 10] = [1, 10, 1, 10, 4, 1, 5, 17, 1, 10];

pub static OilValues: [i32; 10] = [500, 2500, 500, 2500, 1500, 100, 2500, 15000, 500, 2500];

pub static OilMagic: [item_misc_id; 10] = [IMISC_OILACC, IMISC_OILMAST, IMISC_OILSHARP, IMISC_OILDEATH, IMISC_OILSKILL, IMISC_OILBSMTH, IMISC_OILFORT, IMISC_OILPERM, IMISC_OILHARD, IMISC_OILIMP];

pub static OilNames: [&'static str; 10] = ["Oil of Accuracy", "Oil of Mastery", "Oil of Sharpness", "Oil of Death", "Oil of Skill", "Blacksmith Oil", "Oil of Fortitude", "Oil of Permanence", "Oil of Hardening", "Oil of Imperviousness"];

pub static ItemDropNames: [&'static str; 43] = ["armor2", "axe", "fbttle", "bow", "goldflip", "helmut", "mace", "shield", "swrdflip", "rock", "cleaver", "staff", "ring", "crownf", "larmor", "wshield", "scroll", "fplatear", "fbook", "food", "fbttlebb", "fbttledy", "fbttleor", "fbttlebr", "fbttlebl", "fbttleby", "fbttlewh", "fbttledb", "fear", "fbrain", "fmush", "innsign", "bldstn", "fanvil", "flazstaf", "bombs1", "halfps1", "wholeps1", "runes1", "teddys1", "cows1", "donkys1", "mooses1"];

pub static ItemAnimLs: [i8; 43] = [15, 13, 16, 13, 10, 13, 13, 13, 13, 10, 13, 13, 13, 13, 13, 13, 13, 13, 13, 1, 16, 16, 16, 16, 16, 16, 16, 16, 13, 12, 12, 13, 13, 13, 8, 10, 16, 16, 10, 10, 15, 15, 15];

pub static ItemDropSnds: [SfxId; 43] = [IS_FHARM, IS_FAXE, IS_FPOT, IS_FBOW, IS_GOLD, IS_FCAP, IS_FSWOR, IS_FSHLD, IS_FSWOR, IS_FROCK, IS_FAXE, IS_FSTAF, IS_FRING, IS_FCAP, IS_FLARM, IS_FSHLD, IS_FSCRL, IS_FHARM, IS_FBOOK, IS_FLARM, IS_FPOT, IS_FPOT, IS_FPOT, IS_FPOT, IS_FPOT, IS_FPOT, IS_FPOT, IS_FPOT, IS_FBODY, IS_FBODY, IS_FMUSH, IS_FSIGN, IS_FBLST, IS_FANVL, IS_FSTAF, IS_FROCK, IS_FSCRL, IS_FSCRL, IS_FROCK, IS_FMUSH, IS_FHARM, IS_FLARM, IS_FLARM];

pub static premiumlvladd: [i32; 6] = [-1, -1, 0, 0, 1, 2];

pub static premiumLvlAddHellfire: [i32; 15] = [-1, -1, -1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3];
