//! `Source/engine/events.cpp` and `Source/controls/input.h`: fetching input events.

use crate::ctx::Ctx;
use crate::platform::events::Event;

/// Original: `devilution::PollEvent` (controls/input.h).
// @port controls/input.h|devilution::PollEvent(SDL_Event *event) sha=082b8e74ec53
pub fn poll_event(ctx: &mut Ctx) -> Option<Event> {
    let event = ctx.platform.poll_event()?;
    crate::controls::controller::unlock_controller_state(ctx, &event);
    crate::controls::controller::process_controller_motion(ctx, &event);
    Some(event)
}

/// `EventHandler`
pub type EventHandler = fn(&mut Ctx, &Event, u16);

/// Globals of engine/events.cpp.
#[derive(Default)]
pub struct EventsState {
    /// `CurrentEventHandler`
    pub current_event_handler: Option<EventHandler>,
}

/// Original: `FalseAvail` (engine/events.cpp).
// @port engine/events.cpp|devilution::FalseAvail(const char *name, int value) sha=1e3d98c6b7b9
fn false_avail(name: &str, value: i32) -> bool {
    crate::platform::log::verbose!("Unhandled SDL event: {name} {value}");
    true
}

/// Original: `FetchMessage_Real` (engine/events.cpp). Touch, controller-hotplug and window
/// events the platform layer does not produce are left out; `None` means no event was
/// available, `Some(None)` an event that was consumed without producing one.
// @port engine/events.cpp|devilution::FetchMessage_Real(SDL_Event *event, uint16_t *modState) sha=b7289996a57c
fn fetch_message_real(ctx: &mut Ctx) -> Option<(Option<Event>, u16)> {
    let e = poll_event(ctx)?;
    let mod_state = ctx.platform.mod_state();
    match e {
        Event::Quit | Event::Custom(_) | Event::TestWarp(_) => Some((Some(e), mod_state)),
        Event::KeyDown { key, .. } | Event::KeyUp { key, .. } if key == crate::platform::events::keys::SDLK_UNKNOWN => {
            // Erroneous events generated by RG350 kernel.
            Some((None, mod_state))
        }
        Event::KeyDown { key, .. } | Event::KeyUp { key, .. } if key == -1 => {
            let name = if matches!(e, Event::KeyDown { .. }) { "SDL_KEYDOWN" } else { "SDL_KEYUP" };
            false_avail(name, key);
            Some((None, mod_state))
        }
        Event::MouseWheel { x, y } => {
            use crate::platform::events::keys::*;
            let ctrl = (mod_state & crate::platform::events::KMOD_CTRL) != 0;
            // SDL_KEYDOWN with the keysym left at 0 when the wheel did not move.
            let key = if y > 0 {
                if ctrl { SDLK_KP_PLUS } else { SDLK_UP }
            } else if y < 0 {
                if ctrl { SDLK_KP_MINUS } else { SDLK_DOWN }
            } else if x > 0 {
                SDLK_LEFT
            } else if x < 0 {
                SDLK_RIGHT
            } else {
                0
            };
            Some((Some(Event::KeyDown { key, mods: mod_state }), mod_state))
        }
        _ => Some((Some(e), mod_state)),
    }
}

/// Original: `devilution::SetEventHandler` (engine/events.cpp).
// @port engine/events.cpp|devilution::SetEventHandler(EventHandler eventHandler) sha=d1209a4017ac
pub fn set_event_handler(ctx: &mut Ctx, event_handler: Option<EventHandler>) -> Option<EventHandler> {
    crate::options::padmapper_release_all_active_buttons(ctx);
    let previous_handler = ctx.events.current_event_handler;
    ctx.events.current_event_handler = event_handler;
    previous_handler
}

/// Original: `devilution::FetchMessage` (engine/events.cpp). Returns `None` when no event is
/// available; an inner `None` is an event that was consumed (the original's zeroed event).
// @port engine/events.cpp|devilution::FetchMessage(SDL_Event *event, uint16_t *modState) sha=4cb952427a3c
pub fn fetch_message(ctx: &mut Ctx) -> Option<(Option<Event>, u16)> {
    let available = if crate::engine::demomode::is_running(ctx) { crate::engine::demomode::fetch_message(ctx) } else { fetch_message_real(ctx) };
    if let Some((ev, m)) = &available {
        if crate::engine::demomode::is_recording(ctx) {
            crate::engine::demomode::record_message(ctx, ev.as_ref(), *m);
        }
    }
    available
}

/// Original: `devilution::HandleMessage` (engine/events.cpp).
// @port engine/events.cpp|devilution::HandleMessage(const SDL_Event &event, uint16_t modState) sha=927010ff4918
pub fn handle_message(ctx: &mut Ctx, event: &Event, mod_state: u16) {
    let handler = ctx.events.current_event_handler.expect("CurrentEventHandler");
    handler(ctx, event, mod_state);
}
