"""Generate tests/random_parity.rs from DevilutionX 1.5.3's test/random_test.cpp.

  python tools/gen_random_tests.py

The C++ tests pin the vanilla LCG and its distributions (including the negative results caused
by the original's abs/shift/modulo order). The statements follow a few fixed patterns, translated
one by one; anything else stops the script.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "..", "Decomp", "source_1.5.3", "test", "random_test.cpp")


def num(v):
    v = v.strip()
    v = v.replace("std::numeric_limits<int32_t>::min()", "i32::MIN").replace("std::numeric_limits<int32_t>::max()", "i32::MAX")
    v = v.replace("initialSeed", "initial_seed").replace("expectedState", "expected_state")
    return re.sub(r"(\d+)U\b", r"\1", v)


def translate(line):
    line = re.sub(r"\s*//.*$", "", line).strip()
    line = re.sub(r"\s*<<\s*\".*$", ";", line) if "<<" in line and not line.endswith(";") else re.sub(r"\s*<<.*;$", ";", line)
    if not line:
        return None
    m = re.fullmatch(r"SetRndSeed\((.*)\);", line)
    if m:
        return f"r.set_rnd_seed(({num(m.group(1))}) as u32);"
    m = re.fullmatch(r"DiscardRandomValues\((.*)\);", line)
    if m:
        return f"r.discard_random_values({num(m.group(1))});"
    m = re.fullmatch(r"(?:ASSERT|EXPECT)_(EQ|NE)\((.*)\);", line)
    if m:
        args = [a.strip() for a in re.split(r",(?![^(]*\))", m.group(2))]
        a, b = args
        a = a.replace("GenerateSeed()", "r.generate_seed()").replace("AdvanceRndSeed()", "r.advance_rnd_seed()")
        a = re.sub(r"GenerateRnd\((.*)\)", lambda mm: f"r.generate_rnd({num(mm.group(1))})", a)
        a = a.replace("GetLCGEngineState()", "r.lcg_engine_state()")
        b = num(b).replace("initialSeed", "initial_seed").replace("expectedState", "expected_state")
        if "lcg_engine_state" in a:
            b = f"({b}) as u32"
        op = "assert_eq" if m.group(1) == "EQ" else "assert_ne"
        return f"{op}!({a}, {b});"
    m = re.fullmatch(r"(?:uint32_t |auto )?(\w+) = (.*);", line)
    if m:
        name = {"initialSeed": "initial_seed", "expectedState": "expected_state"}.get(m.group(1), m.group(1))
        value = m.group(2).replace("::testing::UnitTest::GetInstance()->random_seed()", "0x1234_5678")
        decl = "let " if line.startswith(("uint32_t", "auto")) else ""
        return f"{decl}{'mut ' if name == 'expected_state' and decl else ''}{name} = ({num(value)}) as u32;" if name in ("initial_seed", "expected_state") else None
    m = re.fullmatch(r"for \((?:auto|int) i = (\d+); i < (\d+); i(\+\+|\s*\*=\s*2)\)( \{)?", line)
    if m:
        if "*=" in m.group(3):
            return f"let mut i = {m.group(1)};\n    while i < {m.group(2)} {{"
        return f"for _i in {m.group(1)}..{m.group(2)} {{" + ("" if m.group(4) else "  // single statement")
    m = re.fullmatch(r"for \(int i : \{ (.*) \}\) \{", line)
    if m:
        return f"for i in [{m.group(1)}] {{"
    if line in ("{", "}"):
        return line
    if line.startswith("constexpr auto maxBound"):
        return "let max_bound = 32767;"
    if line.startswith(("constexpr uint32_t multiplicand", "constexpr uint32_t increment")):
        n, v = re.match(r"constexpr uint32_t (\w+) = (\d+);", line).groups()
        return f"let {n}: u32 = {v};"
    raise SystemExit(f"untranslated: {line}")


def main():
    text = open(SRC, encoding="utf-8").read()
    out = ["//! Generated by `tools/gen_random_tests.py` from DevilutionX 1.5.3's test/random_test.cpp. Do not edit.",
           "", "#![allow(unused_mut, clippy::identity_op, clippy::erasing_op)]", "", "use diablo1_rs::engine::random::DiabloRng;", ""]
    for m in re.finditer(r"TEST\((\w+), (\w+)\)\n\{\n(.*?)\n\}\n", text, re.S):
        out.append("#[test]")
        out.append(f"fn {re.sub(r'(?<=[a-z0-9])([A-Z])', r'_\1', m.group(2)).lower()}() {{")
        out.append("    let mut r = DiabloRng::default();")
        body = m.group(3).replace("\n\t    <<", " <<").replace("\n\t\t    <<", " <<")
        pending_while = False
        close_after_next = False
        for line in body.split("\n"):
            t = translate(line)
            if t is None:
                continue
            t = t.replace("maxBound", "max_bound")
            if close_after_next:
                out.append("        " + t)
                out.append("    }")
                close_after_next = False
                continue
            if t.endswith("// single statement"):
                close_after_next = True
                t = t.replace("  // single statement", "")
            if t.startswith("let mut i =") and "while" in t:
                pending_while = True
            if t == "}" and pending_while:
                out.append("        i *= 2;")
                pending_while = False
            out.append("    " + t)
        out.append("}")
        out.append("")
    path = os.path.join(ROOT, "tests", "random_parity.rs")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(path)


if __name__ == "__main__":
    main()
