"""Generate src/diablo_ui/text_lines.rs (CreditLines, SupportLines) from DevilutionX 1.5.3.

  python tools/gen_text_lines.py

Reads Source/DiabloUI/credits_lines.cpp and support_lines.cpp. `N_("...")` marks a translatable
line; the port keeps the untranslated key (translation happens at use, as in the original).
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "..", "Decomp", "source_1.5.3", "Source", "DiabloUI")


def lines(name, array):
    text = open(os.path.join(SRC, name), encoding="utf-8").read()
    body = re.search(r"const char \*const " + array + r"\[\] = \{(.*?)\n\};", text, re.S).group(1)
    out = []
    for m in re.finditer(r'(?:N_\()?"((?:[^"\\]|\\.)*)"\)?\s*,?', body):
        out.append(m.group(1).encode("utf-8").decode("unicode_escape").encode("latin-1").decode("utf-8"))
    return out


def rust_str(s):
    return json.dumps(s, ensure_ascii=False).replace("\t", "\\t")


def main():
    out = [
        "//! Generated by `tools/gen_text_lines.py` from `Source/DiabloUI/credits_lines.cpp` and",
        "//! `support_lines.cpp` (DevilutionX 1.5.3). Do not edit.",
        "",
    ]
    for name, array, rust in (("credits_lines.cpp", "CreditLines", "CREDIT_LINES"), ("support_lines.cpp", "SupportLines", "SUPPORT_LINES")):
        ls = lines(name, array)
        out.append(f"/// `{array}`")
        out.append(f"pub const {rust}: [&str; {len(ls)}] = [")
        out.extend(f"    {rust_str(s)}," for s in ls)
        out.append("];")
        out.append("")
    path = os.path.join(ROOT, "src", "diablo_ui", "text_lines.rs")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(path)


if __name__ == "__main__":
    main()
