"""Generate src/effects_data.rs (the `_sfx_id` enum values and the `sgSFX` table) from the
DevilutionX 1.5.3 snapshot (Source/effects.h, Source/effects.cpp).

Usage: python tools/gen_sfx.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CRATE = os.path.dirname(HERE)
SRC = os.path.join(CRATE, '..', 'Decomp', 'source_1.5.3', 'Source')


def main():
    header = open(os.path.join(SRC, 'effects.h'), encoding='utf-8').read()
    body = header[header.index('enum _sfx_id'):]
    body = body[body.index('{') + 1:body.index('};')]
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    names = []
    for line in body.splitlines():
        line = line.split('//')[0].strip().rstrip(',')
        if not line or line.startswith('#'):
            continue
        if '=' in line:
            assert line.replace(' ', '') == 'SFX_NONE=-1', line
            continue
        names.append(line)

    cpp = open(os.path.join(SRC, 'effects.cpp'), encoding='utf-8').read()
    table = cpp[cpp.index('TSFX sgSFX[] = {'):]
    table = table[:table.index('\n};')]
    table = '\n'.join(l for l in table.splitlines() if not l.lstrip().startswith('//'))
    rows = re.findall(r'/\*(\w+)\*/\s*\{\s*([^,]+),\s*"([^"]*)"\s*,\s*nullptr\s*\}', table)
    assert len(rows) == len(names), (len(rows), len(names))
    for (n, _, _), e in zip(rows, names):
        assert n == e, (n, e)

    out = ['//! Generated by `tools/gen_sfx.py` from `Source/effects.h` and `Source/effects.cpp`',
           '//! (DevilutionX 1.5.3). Do not edit.', '',
           '#![allow(non_upper_case_globals)]', '',
           'use crate::effects::{sfx_HELLFIRE, sfx_MISC, sfx_MONK, sfx_ROGUE, sfx_SORCERER, sfx_STREAM, sfx_UI, sfx_WARRIOR};', '',
           '/// `_sfx_id`', 'pub type SfxId = i16;', '']
    for i, n in enumerate(names):
        out.append(f'pub const {n}: SfxId = {i};')
    out.append('pub const SFX_NONE: SfxId = -1;')
    out.append(f'pub const NUM_SFX: usize = {len(names)};')
    out.append('')
    out.append('/// `sgSFX`: (bFlags, pszName)')
    out.append('pub static SFX_DATA: [(u8, &str); NUM_SFX] = [')
    for _, flags, path in rows:
        flags = ' | '.join(f.strip() for f in flags.split('|'))
        out.append(f'    ({flags}, "{path.replace(chr(92) * 2, chr(92) * 2)}"),')
    out.append('];')
    out.append('')
    with open(os.path.join(CRATE, 'src', 'effects_data.rs'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    print(f'{len(names)} sound effects')


if __name__ == '__main__':
    main()
