"""Generate Rust constants for the data tables of the level generators.

  python tools/gen_level_data.py

Reads the `const Miniset`, `const uint8_t X[N]`, `int X[A][B]` and `const ShadowStruct X[N]`
definitions at file scope of Source/levels/drlg_l2.cpp, drlg_l3.cpp and drlg_l4.cpp
(DevilutionX 1.5.3) and writes src/levels/<name>_data.rs. Arrays declared with fewer
initialisers than elements are zero-padded, as in C++.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "..", "Decomp", "source_1.5.3", "Source", "levels")


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def numbers(s):
    return [int(v) for v in re.findall(r"-?\d+", s)]


def rows(block):
    """The innermost `{ ... }` groups of a brace block, as lists of numbers."""
    return [numbers(r) for r in re.findall(r"\{([^{}]*)\}", block)]


def gen(name):
    text = strip_comments(open(os.path.join(SRC, f"{name}.cpp"), encoding="utf-8").read())
    out = [
        f"//! Generated by `tools/gen_level_data.py` from `Source/levels/{name}.cpp` (DevilutionX 1.5.3). Do not edit.",
        "",
        "#![allow(non_upper_case_globals, dead_code)]",
        "",
        "use crate::engine::geometry::Size;",
        "use crate::levels::gendung::{Miniset, ShadowStruct};",
        "",
    ]
    # Minisets: const Miniset NAME { { w, h }, { rows }, { rows } };
    for m in re.finditer(r"const Miniset (\w+) \{(.*?)\n\};", text, re.S):
        mname, body = m.group(1), m.group(2)
        size = numbers(re.search(r"\{\s*(\d+\s*,\s*\d+)\s*\}", body).group(1))
        w, h = size
        # the two row blocks follow the size
        rest = body[re.search(r"\{\s*\d+\s*,\s*\d+\s*\}", body).end():]
        groups = re.findall(r"\{((?:\s*\{[^{}]*\}\s*,?)+)\s*\}", rest)
        assert len(groups) == 2, mname
        search, replace = rows(groups[0]), rows(groups[1])
        assert len(search) == h and len(replace) == h, mname

        def grid(rs):
            full = [r + [0] * (6 - len(r)) for r in rs] + [[0] * 6] * (6 - len(rs))
            return "[" + ", ".join("[" + ", ".join(str(v) for v in r) + "]" for r in full) + "]"

        out.append(f"pub const {mname}: Miniset = Miniset {{ size: Size::new({w}, {h}), search: {grid(search)}, replace: {grid(replace)} }};")
    out.append("")
    # Byte tables: const uint8_t NAME[N] = { ... };
    for m in re.finditer(r"const uint8_t (\w+)\[(\d+)\] = \{(.*?)\};", text, re.S):
        tname, n, body = m.group(1), int(m.group(2)), numbers(m.group(3))
        body += [0] * (n - len(body))
        out.append(f"pub const {tname}: [u8; {n}] = [{', '.join(map(str, body))}];")
    # Two-dimensional int tables: int NAME[A][B] = { ... };
    for m in re.finditer(r"^int (\w+)\[(\d+)\]\[(\d+)\] = \{(.*?)\n\};", text, re.S | re.M):
        tname, a, b = m.group(1), int(m.group(2)), int(m.group(3))
        rs = rows(m.group(4))
        rs = [r + [0] * (b - len(r)) for r in rs] + [[0] * b] * (a - len(rs))
        out.append(f"pub const {tname}: [[i32; {b}]; {a}] = [{', '.join('[' + ', '.join(map(str, r)) + ']' for r in rs)}];")
    # Shadow tables: const ShadowStruct NAME[N] = { ... };
    for m in re.finditer(r"const ShadowStruct (\w+)\[(\d+)\] = \{(.*?)\};", text, re.S):
        tname, n = m.group(1), int(m.group(2))
        rs = rows(m.group(3))
        assert len(rs) == n, tname
        items = ", ".join(f"ShadowStruct {{ strig: {r[0]}, s1: {r[1]}, s2: {r[2]}, s3: {r[3]}, nv1: {r[4]}, nv2: {r[5]}, nv3: {r[6]} }}" for r in rs)
        out.append(f"pub const {tname}: [ShadowStruct; {n}] = [{items}];")
    path = os.path.join(ROOT, "src", "levels", f"{name}_data.rs")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print(path)


for n in ("drlg_l2", "drlg_l3", "drlg_l4"):
    gen(n)
