"""Generate tests/pack_parity_data.rs from DevilutionX 1.5.3's test/pack_test.cpp.

  python tools/gen_pack_tests.py

The C++ test regenerates items from their packed form (seed, create info, item index, ...) and
compares every field with what DevilutionX produced. This script copies the packed items and the
expected item fields (PackedDiabloItems/DiabloItems, the spawn, multiplayer and Hellfire tables)
into Rust; the test bodies live in tests/pack_parity.rs.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "..", "Decomp", "source_1.5.3", "test", "pack_test.cpp")

FIELDS = [
    "_iIName", "_itype", "_iClass", "_iCurs", "_iIvalue", "_iMinDam", "_iMaxDam", "_iAC", "_iFlags", "_iMiscId", "_iSpell",
    "_iCharges", "_iMaxCharges", "_iDurability", "_iMaxDur", "_iPLDam", "_iPLToHit", "_iPLAC", "_iPLStr", "_iPLMag", "_iPLDex",
    "_iPLVit", "_iPLFR", "_iPLLR", "_iPLMR", "_iPLMana", "_iPLHP", "_iPLDamMod", "_iPLGetHit", "_iPLLight", "_iSplLvlAdd",
    "_iUid", "_iFMinDam", "_iFMaxDam", "_iLMinDam", "_iLMaxDam", "_iPrePower", "_iSufPower", "_iMinStr", "_iMinMag",
    "_iMinDex", "IDidx",
]


def strip_comments(s):
    return re.sub(r"//[^\n]*", "", s)


def const_name(name):
    """PackedDiabloMPItems -> PACKED_DIABLO_MP_ITEMS"""
    s = re.sub(r"(?<=[a-z])([A-Z])", r"_\1", name)
    s = re.sub(r"(?<=[A-Z])([A-Z][a-z])", r"_\1", s)
    return s.upper()


def rust_expr(v, field):
    v = v.strip().replace("ItemSpecialEffect::None", "ItemSpecialEffect::None_")
    if field == "_iFlags" and "|" in v:
        # BitOr is not const: combine the raw values
        return "ItemSpecialEffect(" + " | ".join(p.strip() + ".0" for p in v.split("|")) + ")"
    if field not in ("_iIName", "_itype", "_iFlags", "_iSpell"):
        return f"({v}) as {'i8' if field in ('_iSplLvlAdd', '_iPrePower', '_iSufPower', '_iMinStr', '_iMinDex') else 'u8' if field == '_iMinMag' else 'i32'}"
    return v


def split_top(s):
    """Split on commas outside braces and quotes."""
    out, cur, depth, quote = [], "", 0, False
    for ch in s:
        if ch == '"':
            quote = not quote
        if not quote and ch == "{":
            depth += 1
        if not quote and ch == "}":
            depth -= 1
        if ch == "," and depth == 0 and not quote:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return [c.strip() for c in out]


def rows(text, name, kind):
    m = re.search(kind + r" " + name + r"\[\] = \{(.*?)\n\};", text, re.S)
    body = strip_comments(m.group(1))
    return [r.strip() for r in re.findall(r"\{([^{}]*)\}", body)]


def main():
    text = open(SRC, encoding="utf-8").read()
    consts = dict(re.findall(r"constexpr ItemSpecialEffect (\w+) = ([^;]+);", text))
    out = [
        "//! Generated by `tools/gen_pack_tests.py` from DevilutionX 1.5.3's test/pack_test.cpp. Do not edit.",
        "",
        "#![allow(dead_code, non_upper_case_globals)]",
        "",
        "use diablo1_rs::enums::*;",
        "use diablo1_rs::pack::ItemPack;",
        "",
        "pub struct TestItem {",
    ]
    types = {"_iIName": "&'static str", "_itype": "ItemType", "_iFlags": "ItemSpecialEffect", "_iSpell": "SpellID", "_iSplLvlAdd": "i8",
             "_iPrePower": "i8", "_iSufPower": "i8", "_iMinStr": "i8", "_iMinMag": "u8", "_iMinDex": "i8"}
    for f in FIELDS:
        out.append(f"    pub {f}: {types.get(f, 'i32')},")
    out.append("}")
    out.append("")
    for name, value in consts.items():
        out.append(f"pub const {name}: ItemSpecialEffect = ItemSpecialEffect({' | '.join('ItemSpecialEffect::' + p.split('::')[1] + '.0' for p in value.split('|'))});")
    out.append("")
    count = 0
    for packed, expected in (("PackedDiabloItems", "DiabloItems"), ("PackedSpawnItems", "SpawnItems"),
                             ("PackedDiabloMPItems", "DiabloMPItems"), ("PackedHellfireItems", "HellfireItems")):
        p = rows(text, packed, "const ItemPack")
        e = rows(text, expected, "const TestItemStruct")
        assert len(p) == len(e), packed
        out.append(f"pub const {const_name(packed)}: [ItemPack; {len(p)}] = [")
        for r in p:
            v = [x.strip() for x in r.split(",")]
            names = ["iSeed", "iCreateInfo", "idx", "bId", "bDur", "bMDur", "bCh", "bMCh", "wValue", "dwBuff"]
            casts = {"iCreateInfo": "u16", "idx": "u16", "wValue": "u16", "dwBuff": "u32"}
            fields = ", ".join(f"{n}: ({x}) as {casts[n]}" if n in casts else f"{n}: {x}" for n, x in zip(names, v))
            out.append(f"    ItemPack {{ {fields} }},")
        out.append("];")
        out.append(f"pub const {const_name(expected)}: [TestItem; {len(e)}] = [")
        for r in e:
            v = split_top(r)
            assert len(v) == len(FIELDS), (expected, r)
            fields = ", ".join(f"{f}: {rust_expr(x, f)}" for f, x in zip(FIELDS, v))
            out.append(f"    TestItem {{ {fields} }},")
        out.append("];")
        out.append("")
        count += len(p)
    path = os.path.join(ROOT, "tests", "pack_parity_data", "mod.rs")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{count} items -> {path}")


if __name__ == "__main__":
    main()
