"""Generate tests/drlg_parity.rs from DevilutionX 1.5.3's dungeon generation tests.

  python tools/gen_drlg_tests.py

Reads test/drlg_l1_test.cpp .. drlg_l4_test.cpp: each TEST loads an expected level
(test/fixtures/{diablo,hellfire}/<level>-<seed>.dun), sets up quests, generates the dungeon for
the seed and entry, and checks every tile, every room/region index and the player's start
position. The Rust tests read the fixtures from the DevilutionX source folder (not copied into
the repository) and skip when it is missing.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TESTS = os.path.join(ROOT, "..", "Decomp", "source_1.5.3", "test")


def snake(name):
    s = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name)
    return s.lower()


def translate(stmt):
    stmt = re.sub(r"\s*//.*$", "", stmt.strip())
    m = re.fullmatch(r"TestInitGame\((.*)\);", stmt)
    if m:
        args = [a.strip() for a in m.group(1).split(",") if a.strip()]
        full = args[0] if len(args) > 0 else "true"
        orig = args[1] if len(args) > 1 else "true"
        return f"t.init_game({full}, {orig});"
    m = re.fullmatch(r"Quests\[(\w+)\]\.(_qactive|_qlevel) = (\w+);", stmt)
    if m:
        return f"t.ctx.quests.Quests[{m.group(1)} as usize].{m.group(2)} = {m.group(3)};"
    if stmt == "InitQuests();":
        return "diablo1_rs::quests::init_quests(&mut t.ctx);"
    if stmt == 'paths::SetAssetsPath(paths::BasePath() + "/assets");':
        return "if !t.use_source_assets() {\n        return;\n    }"
    m = re.fullmatch(r'LoadExpectedLevelData\("([^"]+)"\);', stmt)
    if m:
        return f'if !t.load_expected("{m.group(1)}") {{\n        return;\n    }}'
    m = re.fullmatch(r"TestCreateDungeon\((\d+), (\d+), (\w+)\);", stmt)
    if m:
        return f"t.create_dungeon({m.group(1)}, {m.group(2)}, {m.group(3)});"
    m = re.fullmatch(r"EXPECT_EQ\(ViewPosition, Point\((\d+), (\d+)\)\);", stmt)
    if m:
        return f"assert_eq!(t.ctx.gendung.ViewPosition, Point::new({m.group(1)}, {m.group(2)}));"
    m = re.fullmatch(r'EXPECT_EQ\(Quests\[(\w+)\]\.position, Point\((\d+), (\d+)\)\) << "(.*)";', stmt)
    if m:
        return f'assert_eq!(t.ctx.quests.Quests[{m.group(1)} as usize].position, Point::new({m.group(2)}, {m.group(3)}), "{m.group(4)}");'
    raise SystemExit(f"unknown statement: {stmt}")


def main():
    out = [
        "//! Generated by `tools/gen_drlg_tests.py` from DevilutionX 1.5.3's test/drlg_l*_test.cpp. Do not edit.",
        "//!",
        "//! Dungeon generation parity: every tile and room index of the generated level must match the",
        "//! level DevilutionX generated for the same seed (test/fixtures/*.dun in the DevilutionX source).",
        "",
        "#![allow(non_snake_case)]",
        "",
        "mod common;",
        "",
        "use common::drlg::Harness;",
        "use diablo1_rs::engine::geometry::Point;",
        "use diablo1_rs::enums::*;",
        "",
    ]
    count = 0
    for name in ("drlg_l1_test.cpp", "drlg_l2_test.cpp", "drlg_l3_test.cpp", "drlg_l4_test.cpp"):
        text = open(os.path.join(TESTS, name), encoding="utf-8").read()
        for m in re.finditer(r"TEST\((\w+), (\w+)\)\n\{\n(.*?)\n\}\n", text, re.S):
            suite, test, body = m.groups()
            fixture = re.search(r'LoadExpectedLevelData\("([^"]+)"\);', body)
            if not fixture:
                continue
            lines = [l for l in body.split("\n") if l.strip()]
            lines.remove(next(l for l in lines if "LoadExpectedLevelData" in l))  # the first one creates the harness
            out.append("#[test]")
            out.append(f"fn {snake(suite)}_{snake(test)}() {{")
            out.append(f'    let Some(mut t) = Harness::new("{fixture.group(1)}") else {{ return }};')
            for l in lines:
                out.append("    " + translate(l))
            out.append("}")
            out.append("")
            count += 1
    path = os.path.join(ROOT, "tests", "drlg_parity.rs")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{count} tests -> {path}")


if __name__ == "__main__":
    main()
