"""Generate src/tables/misdat.rs from Source/misdat.cpp (DevilutionX 1.5.3).

  python tools/gen_misdat.py

Emits `MissilesData` (with the add/process procedures as function pointers into
`crate::missiles`), the static part of `MissileSpriteData`, `MissileAnimDelays` and
`MissileAnimLengths`. Also prints the procedure names, for `pending_fn!` stubs.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "..", "Decomp", "source_1.5.3", "Source", "misdat.cpp")
OUT = os.path.join(ROOT, "src", "tables", "misdat.rs")

text = open(SRC, encoding="utf-8").read()


def snake(name):
    s = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name)
    s = re.sub(r"(?<=[A-Z])([A-Z][a-z])", r"_\1", s)
    return s.lower()


def table(name):
    m = re.search(name + r"\[\] = \{(.*?)\n\};", text, re.S)
    rows = []
    for line in m.group(1).splitlines():
        line = line.strip()
        mm = re.match(r"/\*(\w+)\*/\s*\{(.*)\},?\s*$", line)
        if mm:
            rows.append((mm.group(1), [c.strip() for c in mm.group(2).split(",")]))
    return rows


procs = set()
lines = []
lines.append("//! Generated by `tools/gen_misdat.py` from `Source/misdat.cpp` (DevilutionX 1.5.3). Do not edit.\n")
lines.append("#![allow(non_snake_case, non_upper_case_globals, clippy::all)]\n")
lines.append("use crate::effects_data::*;")
lines.append("use crate::enums::*;")
lines.append("use crate::missiles::MissileData;\n")
lines.append("type F = MissileDataFlags;")
lines.append("type G = MissileGraphicID;")
lines.append("type D = MissileMovementDistribution;\n")


def fptr(c):
    c = c.strip()
    if c in ("nullptr", "NULL"):
        return "None"
    name = c.lstrip("&")
    procs.add(name)
    return f"Some(crate::missiles::{snake(name)})"


def flags(c):
    parts = [p.strip() for p in c.split("|")]
    return "MissileDataFlags(" + " | ".join(f"F::{p}.0" for p in parts) + ")"


rows = table("MissilesData")
lines.append("/// `MissilesData`: data related to each missile ID.")
lines.append(f"pub static MissilesData: [MissileData; {len(rows)}] = [")
for name, c in rows:
    add, proc_, lsfx, isfx, filenum, fl, mov = c[:7]
    lines.append(
        f"    /*{name}*/ MissileData {{ mAddProc: {fptr(add)}, mProc: {fptr(proc_)}, mlSFX: {lsfx}, miSFX: {isfx}, "
        f"mFileNum: G::{filenum.split('::')[1]}, flags: {flags(fl)}, movementDistribution: D::{mov.split('::')[1]} }},"
    )
lines.append("];\n")

# Anim lengths/delays
consts = dict(re.findall(r"constexpr uint8_t (AnimLen_\w+) = (\d+);", text))


def arr16(block):
    out = []
    for item in re.findall(r"(\{\}|Repeat\(\d+\)|\{[^}]*\})", block):
        if item == "{}":
            vals = [0] * 16
        elif item.startswith("Repeat"):
            vals = [int(re.search(r"\d+", item).group())] * 16
        else:
            vals = [int(v) for v in item.strip("{} ").split(",") if v.strip()]
            vals += [0] * (16 - len(vals))
        out.append(vals)
    return out


for nm in ("MissileAnimDelays", "MissileAnimLengths"):
    m = re.search(r"const std::array<uint8_t, 16> " + nm + r"\[\] \{(.*?)\n\};", text, re.S)
    rows16 = arr16(m.group(1))
    lines.append(f"/// `{nm}`")
    lines.append(f"pub static {nm}: [[u8; 16]; {len(rows16)}] = [")
    for r in rows16:
        lines.append("    [" + ", ".join(map(str, r)) + "],")
    lines.append("];\n")

srows = table("MissileSpriteData")
lines.append("/// `MissileFileData`'s static fields.")
lines.append("pub struct MissileFileInfo {")
lines.append("    pub animWidth: u16,")
lines.append("    pub animWidth2: i8,")
lines.append("    pub name: &'static str,")
lines.append("    pub animFAmt: u8,")
lines.append("    pub flags: MissileGraphicsFlags,")
lines.append("    pub animDelayIdx: u8,")
lines.append("    pub animLenIdx: u8,")
lines.append("}\n")
lines.append("/// `MissileSpriteData` (static fields; the loaded sprites live in `MissilesState`).")
lines.append(f"pub static MissileSpriteInfo: [MissileFileInfo; {len(srows)}] = [")
for name, c in srows:
    _, w, w2, nm, famt, fl, delay, ln = c[:8]
    nm = '""' if nm == "{}" else nm
    fl = fl.split("::")[1]
    fl = "None_" if fl == "None" else fl
    ln = consts.get(ln, ln)
    lines.append(
        f"    /*{name}*/ MissileFileInfo {{ animWidth: {w}, animWidth2: {w2}, name: {nm}, animFAmt: {famt}, "
        f"flags: MissileGraphicsFlags::{fl}, animDelayIdx: {delay}, animLenIdx: {ln} }},"
    )
lines.append("];")

open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print("procs:", " ".join(sorted(procs)))
print("wrote", OUT, len(rows), "missiles,", len(srows), "graphics")
