"""Generate src/enums.rs from the enum declarations in the DevilutionX 1.5.3 headers.

  python tools/gen_enums.py

* `enum class X : T { ... }`  -> Rust `enum X` (repr T), aliases (FIRST = ...) become associated consts
* `enum class X` used with `use_enum_as_flags(X)` -> newtype `struct X(pub T)` with associated consts
* plain C `enum x : T { A, B }` -> `pub type x = T;` and `pub const A: x = 0;` (C code uses the bare names)
* anonymous enums -> consts of type i32
Values are evaluated, so every enumerator carries its explicit discriminant.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CRATE = os.path.dirname(HERE)
SRC = os.path.join(CRATE, '..', 'Decomp', 'source_1.5.3', 'Source')

HEADERS = [
    'itemdat.h', 'player.h', 'monster.h', 'monstdat.h', 'quests.h', 'misdat.h', 'levels/gendung.h', 'spelldat.h',
    'objdat.h', 'items.h', 'inv.h', 'effects.h', 'diablo.h', 'interfac.h', 'towners.h', 'textdat.h', 'stores.h',
    'spells.h', 'pfile.h', 'panels/ui_panels.hpp', 'msg.h', 'missiles.h', 'error.h', 'engine/animationinfo.h',
    'engine/render/dun_render.hpp', 'storm/storm_net.hpp', 'engine/render/text_render.hpp',
]
# Defined by hand elsewhere in the crate (or not needed).
SKIP = {
    '_sfx_id', 'sfx_flag', 'dungeon_type', 'MouseActionType', '_music_id', 'cursor_id', 'ControlTypes', 'CursorType',
    'GamepadLayout', 'GameActionType', 'AxisDirectionX', 'AxisDirectionY', 'GameFontTables', 'PanelDrawComponent',
    'Status', 'Type', 'text_color',
}
# Unscoped enums used as bit flags (and with an enumerator named None).
FORCE_FLAGS = {'AnimationDistributionFlags', 'MissileGraphicsFlags'}
RUST_INT = {
    'uint8_t': 'u8', 'int8_t': 'i8', 'uint16_t': 'u16', 'int16_t': 'i16', 'uint32_t': 'u32', 'int32_t': 'i32',
    'int': 'i32', 'unsigned': 'u32', 'std::uint8_t': 'u8', 'std::int8_t': 'i8', '': 'i32',
}


def strip_comments(s):
    s = re.sub(r'/\*.*?\*/', '', s, flags=re.S)
    return re.sub(r'//[^\n]*', '', s)


def find_enums(text):
    """Yield (is_class, name, underlying, body)."""
    for m in re.finditer(r'\benum\s+(class\s+)?([A-Za-z_]\w*)?\s*(?::\s*([\w:]+))?\s*\{', text):
        start = m.end()
        depth = 1
        i = start
        while depth:
            if text[i] == '{':
                depth += 1
            elif text[i] == '}':
                depth -= 1
            i += 1
        yield bool(m.group(1)), m.group(2) or '', (m.group(3) or '').strip(), text[start:i - 1]


def c_eval(expr, env, scope):
    e = expr.strip()
    e = re.sub(r'static_cast<[^>]*>', '', e)
    e = re.sub(r'\b(\d+)[uU]?[lL]*\b', r'\1', e)
    e = re.sub(r'\b0x([0-9a-fA-F]+)[uU]?[lL]*\b', lambda m: str(int(m.group(1), 16)), e)

    def name(m):
        n = m.group(0)
        if '::' in n:
            if n in env:
                return str(env[n])
            n = n.split('::')[-1]
            if n in scope:
                return str(scope[n])
        if n in scope:
            return str(scope[n])
        if n in env:
            return str(env[n])
        raise KeyError(n)

    e = re.sub(r'[A-Za-z_][\w:]*', name, e)
    e = e.replace('/', '//')
    return int(eval(e))


def main():
    flags = set()
    out = ['//! Generated by `tools/gen_enums.py` from the DevilutionX 1.5.3 headers. Do not edit.', '',
           '#![allow(non_camel_case_types, non_upper_case_globals, clippy::upper_case_acronyms)]', '']
    env = {}
    seen = set()
    texts = []
    for h in HEADERS + ['engine/palette.h']:
        raw = open(os.path.join(SRC, h), encoding='utf-8').read()
        for n, v in re.findall(r'^#define\s+([A-Z_][A-Z0-9_]*)\s+(\(?-?\d+\)?)\s*$', raw, flags=re.M):
            env[n] = int(v.strip('()'))
    for h in HEADERS:
        t = strip_comments(open(os.path.join(SRC, h), encoding='utf-8').read())
        flags.update(re.findall(r'use_enum_as_flags\((\w+)\)', t))
        texts.append((h, t))
    for h, t in texts:
        for is_class, name, under, body in find_enums(t):
            if name in SKIP or (name and name in seen):
                continue
            seen.add(name)
            rty = RUST_INT.get(under, None)
            if rty is None:
                raise SystemExit(f'{h}: unknown underlying type {under} for {name}')
            members = []
            scope = {}
            nxt = 0
            for item in [x.strip() for x in body.split(',')]:
                if not item:
                    continue
                if '=' in item:
                    n, v = [x.strip() for x in item.split('=', 1)]
                    val = c_eval(v, env, scope)
                    alias = re.fullmatch(r'[A-Za-z_]\w*', v.strip()) is not None and v.strip() in scope
                else:
                    n, val, alias = item, nxt, False
                if rty.startswith('u') and val < 0:
                    val &= (1 << int(rty[1:])) - 1
                scope[n] = val
                members.append((n, val, alias))
                nxt = val + 1
            out.append(f'// {h}')
            if (is_class and name in flags) or name in FORCE_FLAGS:
                out.append('#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default, PartialOrd, Ord)]')
                out.append(f'pub struct {name}(pub {rty});')
                out.append(f'impl {name} {{')
                out.append(f'    pub const None_: {name} = {name}(0);')
                for n, v, _ in members:
                    out.append(f'    pub const {n}: {name} = {name}({v});')
                out.append('    pub const fn has_any_of(self, f: Self) -> bool {\n        self.0 & f.0 != 0\n    }')
                out.append('    pub const fn has_none_of(self, f: Self) -> bool {\n        self.0 & f.0 == 0\n    }')
                out.append('    pub const fn has_all_of(self, f: Self) -> bool {\n        self.0 & f.0 == f.0\n    }')
                out.append('}')
                for op, tr, m in (('|', 'BitOr', 'bitor'), ('&', 'BitAnd', 'bitand'), ('^', 'BitXor', 'bitxor')):
                    out.append(f'impl std::ops::{tr} for {name} {{\n    type Output = {name};\n    fn {m}(self, o: {name}) -> {name} {{\n        {name}(self.0 {op} o.0)\n    }}\n}}')
                    out.append(f'impl std::ops::{tr}Assign for {name} {{\n    fn {m}_assign(&mut self, o: {name}) {{\n        self.0 = self.0 {op} o.0;\n    }}\n}}')
                out.append(f'impl std::ops::Not for {name} {{\n    type Output = {name};\n    fn not(self) -> {name} {{\n        {name}(!self.0)\n    }}\n}}')
            elif is_class:
                real = [(n, v) for n, v, a in members if not a]
                vals = {}
                variants = []
                aliases = []
                for n, v, a in members:
                    if a or v in vals:
                        aliases.append((n, vals.get(v, n)))
                    else:
                        vals[v] = n
                        variants.append((n, v))
                default = vals.get(0, variants[0][0])
                out.append('#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]')
                out.append(f'#[repr({rty})]')
                out.append(f'pub enum {name} {{')
                for n, v in variants:
                    out.append(f'    {n} = {v},')
                out.append('}')
                out.append(f'impl Default for {name} {{\n    fn default() -> Self {{\n        {name}::{default}\n    }}\n}}')
                out.append(f'impl {name} {{')
                for n, target in aliases:
                    out.append(f'    pub const {n}: {name} = {name}::{target};')
                out.append(f'    pub const fn from_repr(v: {rty}) -> Option<{name}> {{\n        match v {{')
                for n, v in variants:
                    out.append(f'            {v} => Some({name}::{n}),')
                out.append('            _ => Option::None,\n        }\n    }')
                out.append(f'    /// Panics on a value that is not an enumerator (the C++ cast would be UB-adjacent).')
                out.append(f'    pub fn from_raw(v: {rty}) -> {name} {{\n        Self::from_repr(v).unwrap_or_else(|| panic!("invalid {name} {{v}}"))\n    }}')
                out.append(f'    pub const fn raw(self) -> {rty} {{\n        self as {rty}\n    }}')
                out.append('}')
                for n, v, _ in members:
                    env[name + '::' + n] = v
            else:
                tname = name if name else None
                if tname:
                    out.append(f'pub type {tname} = {rty};')
                for n, v, _ in members:
                    out.append(f'pub const {n}: {tname or rty} = {v};')
                    env[n] = v
            if not is_class and name:
                pass
            out.append('')
    with open(os.path.join(CRATE, 'src', 'enums.rs'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    print(f'{len(seen)} enums')


if __name__ == '__main__':
    main()
