"""Generate tests/animation_parity.rs from DevilutionX's test/animationinfo_test.cpp.

Each TEST(AnimationInfo, Name) becomes a Rust #[test] that replays the same SetNewAnimation /
GameTick / Rendering steps through `run_animation_test`.

Usage: python tools/gen_anim_tests.py   (DEVILUTIONX_SOURCE defaults to ../Decomp/source_1.5.3)
"""
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(os.environ.get("DEVILUTIONX_SOURCE", ROOT.parent / "Decomp" / "source_1.5.3"))
OUT = ROOT / "tests" / "animation_parity.rs"

HEADER = '''//! Generated by tools/gen_anim_tests.py from DevilutionX 1.5.3's test/animationinfo_test.cpp.
//! Simulates game ticks and renders between them; the animation distribution logic must pick the
//! same frame as the original at every step. Do not edit by hand.

use diablo1_rs::engine::animationinfo::AnimationInfo;
use diablo1_rs::enums::AnimationDistributionFlags as F;

enum Step {
    /// `SetNewAnimationData(numberOfFrames, delayLen, params, numSkippedFrames, distributeFramesBeforeFrame)`
    New(i8, i8, F, i8, i8),
    /// `GameTickData(expectedAnimationFrame, expectedAnimationCnt)`
    Tick(i8, i8),
    /// `RenderingData(fProgressToNextGameTick, expectedRenderingFrame)`
    Render(f32, i8),
}
use Step::*;

/// `RunAnimationTest`
fn run_animation_test(steps: &[Step]) {
    let mut anim = AnimationInfo::default();
    let mut current_game_tick = 0;
    for step in steps {
        match *step {
            New(frames, delay, flags, skipped, before) => anim.set_new_animation(None, frames, delay, flags, skipped, before, 0),
            Tick(frame, cnt) => {
                current_game_tick += 1;
                anim.process_animation(false);
                assert_eq!((anim.currentFrame, anim.tickCounterOfCurrentFrame), (frame, cnt), "GameTick: {current_game_tick}");
            }
            Render(progress, frame) => {
                let progress_to_next_game_tick = (progress * AnimationInfo::BASE_VALUE_FRACTION as f32) as u8;
                assert_eq!(
                    anim.get_frame_to_use_for_rendering(progress_to_next_game_tick),
                    frame,
                    "ProgressToNextGameTick: {progress:.2} currentFrame: {} DelayCounter: {} GameTick: {current_game_tick}",
                    anim.currentFrame,
                    anim.tickCounterOfCurrentFrame
                );
            }
        }
    }
}
'''


def flags(expr: str) -> str:
    names = re.findall(r"AnimationDistributionFlags::(\w+)", expr)
    if not names:
        return "F::None"
    return "F(" + " | ".join(f"F::{n}.0" for n in names) + ")"


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def split_args(s: str) -> list[str]:
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def main() -> None:
    text = (SRC / "test" / "animationinfo_test.cpp").read_text(encoding="utf-8")
    out = [HEADER]
    count = 0
    for m in re.finditer(r"TEST\(AnimationInfo, (\w+)\)(.*?)\n\}", text, re.S):
        name, body = m.group(1), m.group(2)
        comment = body.split("\n", 1)[0].strip()
        out.append("")
        if comment.startswith("//"):
            out.append("/// " + comment[2:].strip())
        out.append("#[test]")
        out.append(f"fn {snake(name)}() {{")
        out.append("    run_animation_test(&[")
        for line in body.splitlines():
            line = line.strip()
            if line.startswith("//"):
                out.append("        " + line)
                continue
            s = re.match(r"new (\w+)\((.*)\),?$", line)
            if not s:
                continue
            kind, args = s.group(1), split_args(s.group(2))
            if kind == "SetNewAnimationData":
                args += [""] * (5 - len(args))
                out.append(f"        New({args[0]}, {args[1]}, {flags(args[2])}, {args[3] or 0}, {args[4] or 0}),")
            elif kind == "GameTickData":
                out.append(f"        Tick({args[0]}, {args[1]}),")
            elif kind == "RenderingData":
                out.append(f"        Render({args[0].rstrip('f')}, {args[1]}),")
            else:
                raise SystemExit(f"unknown step {kind}")
        out.append("    ]);")
        out.append("}")
        count += 1
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({count} tests)")


if __name__ == "__main__":
    main()
