//! Generated by `tools/gen_sfx.py` from `Source/effects.h` and `Source/effects.cpp`
//! (DevilutionX 1.5.3). Do not edit.

#![allow(non_upper_case_globals)]

use crate::effects::{sfx_HELLFIRE, sfx_MISC, sfx_MONK, sfx_ROGUE, sfx_SORCERER, sfx_STREAM, sfx_UI, sfx_WARRIOR};

/// `_sfx_id`
pub type SfxId = i16;

pub const PS_WALK1: SfxId = 0;
pub const PS_BFIRE: SfxId = 1;
pub const PS_TMAG: SfxId = 2;
pub const PS_SWING: SfxId = 3;
pub const PS_SWING2: SfxId = 4;
pub const PS_DEAD: SfxId = 5;
pub const IS_STING1: SfxId = 6;
pub const IS_FBALLBOW: SfxId = 7;
pub const IS_QUESTDN: SfxId = 8;
pub const IS_BARLFIRE: SfxId = 9;
pub const IS_BARREL: SfxId = 10;
pub const IS_POPPOP8: SfxId = 11;
pub const IS_POPPOP5: SfxId = 12;
pub const IS_POPPOP3: SfxId = 13;
pub const IS_POPPOP2: SfxId = 14;
pub const IS_BHIT: SfxId = 15;
pub const IS_BHIT1: SfxId = 16;
pub const IS_CHEST: SfxId = 17;
pub const IS_DOORCLOS: SfxId = 18;
pub const IS_DOOROPEN: SfxId = 19;
pub const IS_FANVL: SfxId = 20;
pub const IS_FAXE: SfxId = 21;
pub const IS_FBLST: SfxId = 22;
pub const IS_FBODY: SfxId = 23;
pub const IS_FBOOK: SfxId = 24;
pub const IS_FBOW: SfxId = 25;
pub const IS_FCAP: SfxId = 26;
pub const IS_FHARM: SfxId = 27;
pub const IS_FLARM: SfxId = 28;
pub const IS_FMUSH: SfxId = 29;
pub const IS_FPOT: SfxId = 30;
pub const IS_FRING: SfxId = 31;
pub const IS_FROCK: SfxId = 32;
pub const IS_FSCRL: SfxId = 33;
pub const IS_FSHLD: SfxId = 34;
pub const IS_FSIGN: SfxId = 35;
pub const IS_FSTAF: SfxId = 36;
pub const IS_FSWOR: SfxId = 37;
pub const IS_GOLD: SfxId = 38;
pub const IS_IANVL: SfxId = 39;
pub const IS_IAXE: SfxId = 40;
pub const IS_IBLST: SfxId = 41;
pub const IS_IBODY: SfxId = 42;
pub const IS_IBOOK: SfxId = 43;
pub const IS_IBOW: SfxId = 44;
pub const IS_ICAP: SfxId = 45;
pub const IS_IGRAB: SfxId = 46;
pub const IS_IHARM: SfxId = 47;
pub const IS_ILARM: SfxId = 48;
pub const IS_IMUSH: SfxId = 49;
pub const IS_IPOT: SfxId = 50;
pub const IS_IRING: SfxId = 51;
pub const IS_IROCK: SfxId = 52;
pub const IS_ISCROL: SfxId = 53;
pub const IS_ISHIEL: SfxId = 54;
pub const IS_ISIGN: SfxId = 55;
pub const IS_ISTAF: SfxId = 56;
pub const IS_ISWORD: SfxId = 57;
pub const IS_LEVER: SfxId = 58;
pub const IS_MAGIC: SfxId = 59;
pub const IS_MAGIC1: SfxId = 60;
pub const IS_RBOOK: SfxId = 61;
pub const IS_SARC: SfxId = 62;
pub const IS_TITLEMOV: SfxId = 63;
pub const IS_TITLSLCT: SfxId = 64;
pub const IS_TRAP: SfxId = 65;
pub const IS_CAST2: SfxId = 66;
pub const IS_CAST4: SfxId = 67;
pub const IS_CAST6: SfxId = 68;
pub const IS_CAST7: SfxId = 69;
pub const IS_CAST8: SfxId = 70;
pub const IS_REPAIR: SfxId = 71;
pub const LS_ACID: SfxId = 72;
pub const LS_ACIDS: SfxId = 73;
pub const LS_APOC: SfxId = 74;
pub const LS_BLODSTAR: SfxId = 75;
pub const LS_BLSIMPT: SfxId = 76;
pub const LS_BONESP: SfxId = 77;
pub const LS_BSIMPCT: SfxId = 78;
pub const LS_CALDRON: SfxId = 79;
pub const LS_CBOLT: SfxId = 80;
pub const LS_DSERP: SfxId = 81;
pub const LS_ELECIMP1: SfxId = 82;
pub const LS_ELEMENTL: SfxId = 83;
pub const LS_ETHEREAL: SfxId = 84;
pub const LS_FBOLT1: SfxId = 85;
pub const LS_FIRIMP2: SfxId = 86;
pub const LS_FLAMWAVE: SfxId = 87;
pub const LS_FOUNTAIN: SfxId = 88;
pub const LS_GOLUM: SfxId = 89;
pub const LS_GSHRINE: SfxId = 90;
pub const LS_GUARD: SfxId = 91;
pub const LS_GUARDLAN: SfxId = 92;
pub const LS_HOLYBOLT: SfxId = 93;
pub const LS_INFRAVIS: SfxId = 94;
pub const LS_INVISIBL: SfxId = 95;
pub const LS_LNING1: SfxId = 96;
pub const LS_MSHIELD: SfxId = 97;
pub const LS_NESTXPLD: SfxId = 98;
pub const LS_NOVA: SfxId = 99;
pub const LS_PUDDLE: SfxId = 100;
pub const LS_RESUR: SfxId = 101;
pub const LS_SCURIMP: SfxId = 102;
pub const LS_SENTINEL: SfxId = 103;
pub const LS_SPOUTSTR: SfxId = 104;
pub const LS_TRAPDIS: SfxId = 105;
pub const LS_TELEPORT: SfxId = 106;
pub const LS_WALLLOOP: SfxId = 107;
pub const LS_LMAG: SfxId = 108;
pub const TSFX_BMAID1: SfxId = 109;
pub const TSFX_BMAID2: SfxId = 110;
pub const TSFX_BMAID3: SfxId = 111;
pub const TSFX_BMAID4: SfxId = 112;
pub const TSFX_BMAID5: SfxId = 113;
pub const TSFX_BMAID6: SfxId = 114;
pub const TSFX_BMAID7: SfxId = 115;
pub const TSFX_BMAID8: SfxId = 116;
pub const TSFX_BMAID9: SfxId = 117;
pub const TSFX_BMAID10: SfxId = 118;
pub const TSFX_BMAID11: SfxId = 119;
pub const TSFX_BMAID12: SfxId = 120;
pub const TSFX_BMAID13: SfxId = 121;
pub const TSFX_BMAID14: SfxId = 122;
pub const TSFX_BMAID15: SfxId = 123;
pub const TSFX_BMAID16: SfxId = 124;
pub const TSFX_BMAID17: SfxId = 125;
pub const TSFX_BMAID18: SfxId = 126;
pub const TSFX_BMAID19: SfxId = 127;
pub const TSFX_BMAID20: SfxId = 128;
pub const TSFX_BMAID21: SfxId = 129;
pub const TSFX_BMAID22: SfxId = 130;
pub const TSFX_BMAID23: SfxId = 131;
pub const TSFX_BMAID24: SfxId = 132;
pub const TSFX_BMAID25: SfxId = 133;
pub const TSFX_BMAID26: SfxId = 134;
pub const TSFX_BMAID27: SfxId = 135;
pub const TSFX_BMAID28: SfxId = 136;
pub const TSFX_BMAID29: SfxId = 137;
pub const TSFX_BMAID30: SfxId = 138;
pub const TSFX_BMAID31: SfxId = 139;
pub const TSFX_BMAID32: SfxId = 140;
pub const TSFX_BMAID33: SfxId = 141;
pub const TSFX_BMAID34: SfxId = 142;
pub const TSFX_BMAID35: SfxId = 143;
pub const TSFX_BMAID36: SfxId = 144;
pub const TSFX_BMAID37: SfxId = 145;
pub const TSFX_BMAID38: SfxId = 146;
pub const TSFX_BMAID39: SfxId = 147;
pub const TSFX_BMAID40: SfxId = 148;
pub const TSFX_SMITH1: SfxId = 149;
pub const TSFX_SMITH2: SfxId = 150;
pub const TSFX_SMITH3: SfxId = 151;
pub const TSFX_SMITH4: SfxId = 152;
pub const TSFX_SMITH5: SfxId = 153;
pub const TSFX_SMITH6: SfxId = 154;
pub const TSFX_SMITH7: SfxId = 155;
pub const TSFX_SMITH8: SfxId = 156;
pub const TSFX_SMITH9: SfxId = 157;
pub const TSFX_SMITH10: SfxId = 158;
pub const TSFX_SMITH11: SfxId = 159;
pub const TSFX_SMITH12: SfxId = 160;
pub const TSFX_SMITH13: SfxId = 161;
pub const TSFX_SMITH14: SfxId = 162;
pub const TSFX_SMITH15: SfxId = 163;
pub const TSFX_SMITH16: SfxId = 164;
pub const TSFX_SMITH17: SfxId = 165;
pub const TSFX_SMITH18: SfxId = 166;
pub const TSFX_SMITH19: SfxId = 167;
pub const TSFX_SMITH20: SfxId = 168;
pub const TSFX_SMITH21: SfxId = 169;
pub const TSFX_SMITH22: SfxId = 170;
pub const TSFX_SMITH23: SfxId = 171;
pub const TSFX_SMITH24: SfxId = 172;
pub const TSFX_SMITH25: SfxId = 173;
pub const TSFX_SMITH26: SfxId = 174;
pub const TSFX_SMITH27: SfxId = 175;
pub const TSFX_SMITH28: SfxId = 176;
pub const TSFX_SMITH29: SfxId = 177;
pub const TSFX_SMITH30: SfxId = 178;
pub const TSFX_SMITH31: SfxId = 179;
pub const TSFX_SMITH32: SfxId = 180;
pub const TSFX_SMITH33: SfxId = 181;
pub const TSFX_SMITH34: SfxId = 182;
pub const TSFX_SMITH35: SfxId = 183;
pub const TSFX_SMITH36: SfxId = 184;
pub const TSFX_SMITH37: SfxId = 185;
pub const TSFX_SMITH38: SfxId = 186;
pub const TSFX_SMITH39: SfxId = 187;
pub const TSFX_SMITH40: SfxId = 188;
pub const TSFX_SMITH41: SfxId = 189;
pub const TSFX_SMITH42: SfxId = 190;
pub const TSFX_SMITH43: SfxId = 191;
pub const TSFX_SMITH44: SfxId = 192;
pub const TSFX_SMITH45: SfxId = 193;
pub const TSFX_SMITH46: SfxId = 194;
pub const TSFX_SMITH47: SfxId = 195;
pub const TSFX_SMITH48: SfxId = 196;
pub const TSFX_SMITH49: SfxId = 197;
pub const TSFX_SMITH50: SfxId = 198;
pub const TSFX_SMITH51: SfxId = 199;
pub const TSFX_SMITH52: SfxId = 200;
pub const TSFX_SMITH53: SfxId = 201;
pub const TSFX_SMITH54: SfxId = 202;
pub const TSFX_SMITH55: SfxId = 203;
pub const TSFX_SMITH56: SfxId = 204;
pub const TSFX_COW1: SfxId = 205;
pub const TSFX_COW2: SfxId = 206;
pub const TSFX_COW7: SfxId = 207;
pub const TSFX_COW8: SfxId = 208;
pub const TSFX_DEADGUY: SfxId = 209;
pub const TSFX_DRUNK1: SfxId = 210;
pub const TSFX_DRUNK2: SfxId = 211;
pub const TSFX_DRUNK3: SfxId = 212;
pub const TSFX_DRUNK4: SfxId = 213;
pub const TSFX_DRUNK5: SfxId = 214;
pub const TSFX_DRUNK6: SfxId = 215;
pub const TSFX_DRUNK7: SfxId = 216;
pub const TSFX_DRUNK8: SfxId = 217;
pub const TSFX_DRUNK9: SfxId = 218;
pub const TSFX_DRUNK10: SfxId = 219;
pub const TSFX_DRUNK11: SfxId = 220;
pub const TSFX_DRUNK12: SfxId = 221;
pub const TSFX_DRUNK13: SfxId = 222;
pub const TSFX_DRUNK14: SfxId = 223;
pub const TSFX_DRUNK15: SfxId = 224;
pub const TSFX_DRUNK16: SfxId = 225;
pub const TSFX_DRUNK17: SfxId = 226;
pub const TSFX_DRUNK18: SfxId = 227;
pub const TSFX_DRUNK19: SfxId = 228;
pub const TSFX_DRUNK20: SfxId = 229;
pub const TSFX_DRUNK21: SfxId = 230;
pub const TSFX_DRUNK22: SfxId = 231;
pub const TSFX_DRUNK23: SfxId = 232;
pub const TSFX_DRUNK24: SfxId = 233;
pub const TSFX_DRUNK25: SfxId = 234;
pub const TSFX_DRUNK26: SfxId = 235;
pub const TSFX_DRUNK27: SfxId = 236;
pub const TSFX_DRUNK28: SfxId = 237;
pub const TSFX_DRUNK29: SfxId = 238;
pub const TSFX_DRUNK30: SfxId = 239;
pub const TSFX_DRUNK31: SfxId = 240;
pub const TSFX_DRUNK32: SfxId = 241;
pub const TSFX_DRUNK33: SfxId = 242;
pub const TSFX_DRUNK34: SfxId = 243;
pub const TSFX_DRUNK35: SfxId = 244;
pub const TSFX_HEALER1: SfxId = 245;
pub const TSFX_HEALER2: SfxId = 246;
pub const TSFX_HEALER3: SfxId = 247;
pub const TSFX_HEALER4: SfxId = 248;
pub const TSFX_HEALER5: SfxId = 249;
pub const TSFX_HEALER6: SfxId = 250;
pub const TSFX_HEALER7: SfxId = 251;
pub const TSFX_HEALER8: SfxId = 252;
pub const TSFX_HEALER9: SfxId = 253;
pub const TSFX_HEALER10: SfxId = 254;
pub const TSFX_HEALER11: SfxId = 255;
pub const TSFX_HEALER12: SfxId = 256;
pub const TSFX_HEALER13: SfxId = 257;
pub const TSFX_HEALER14: SfxId = 258;
pub const TSFX_HEALER15: SfxId = 259;
pub const TSFX_HEALER16: SfxId = 260;
pub const TSFX_HEALER17: SfxId = 261;
pub const TSFX_HEALER18: SfxId = 262;
pub const TSFX_HEALER19: SfxId = 263;
pub const TSFX_HEALER20: SfxId = 264;
pub const TSFX_HEALER21: SfxId = 265;
pub const TSFX_HEALER22: SfxId = 266;
pub const TSFX_HEALER23: SfxId = 267;
pub const TSFX_HEALER24: SfxId = 268;
pub const TSFX_HEALER25: SfxId = 269;
pub const TSFX_HEALER26: SfxId = 270;
pub const TSFX_HEALER27: SfxId = 271;
pub const TSFX_HEALER28: SfxId = 272;
pub const TSFX_HEALER29: SfxId = 273;
pub const TSFX_HEALER30: SfxId = 274;
pub const TSFX_HEALER31: SfxId = 275;
pub const TSFX_HEALER32: SfxId = 276;
pub const TSFX_HEALER33: SfxId = 277;
pub const TSFX_HEALER34: SfxId = 278;
pub const TSFX_HEALER35: SfxId = 279;
pub const TSFX_HEALER36: SfxId = 280;
pub const TSFX_HEALER37: SfxId = 281;
pub const TSFX_HEALER38: SfxId = 282;
pub const TSFX_HEALER39: SfxId = 283;
pub const TSFX_HEALER40: SfxId = 284;
pub const TSFX_HEALER41: SfxId = 285;
pub const TSFX_HEALER42: SfxId = 286;
pub const TSFX_HEALER43: SfxId = 287;
pub const TSFX_HEALER44: SfxId = 288;
pub const TSFX_HEALER45: SfxId = 289;
pub const TSFX_HEALER46: SfxId = 290;
pub const TSFX_HEALER47: SfxId = 291;
pub const TSFX_PEGBOY1: SfxId = 292;
pub const TSFX_PEGBOY2: SfxId = 293;
pub const TSFX_PEGBOY3: SfxId = 294;
pub const TSFX_PEGBOY4: SfxId = 295;
pub const TSFX_PEGBOY5: SfxId = 296;
pub const TSFX_PEGBOY6: SfxId = 297;
pub const TSFX_PEGBOY7: SfxId = 298;
pub const TSFX_PEGBOY8: SfxId = 299;
pub const TSFX_PEGBOY9: SfxId = 300;
pub const TSFX_PEGBOY10: SfxId = 301;
pub const TSFX_PEGBOY11: SfxId = 302;
pub const TSFX_PEGBOY12: SfxId = 303;
pub const TSFX_PEGBOY13: SfxId = 304;
pub const TSFX_PEGBOY14: SfxId = 305;
pub const TSFX_PEGBOY15: SfxId = 306;
pub const TSFX_PEGBOY16: SfxId = 307;
pub const TSFX_PEGBOY17: SfxId = 308;
pub const TSFX_PEGBOY18: SfxId = 309;
pub const TSFX_PEGBOY19: SfxId = 310;
pub const TSFX_PEGBOY20: SfxId = 311;
pub const TSFX_PEGBOY21: SfxId = 312;
pub const TSFX_PEGBOY22: SfxId = 313;
pub const TSFX_PEGBOY23: SfxId = 314;
pub const TSFX_PEGBOY24: SfxId = 315;
pub const TSFX_PEGBOY25: SfxId = 316;
pub const TSFX_PEGBOY26: SfxId = 317;
pub const TSFX_PEGBOY27: SfxId = 318;
pub const TSFX_PEGBOY28: SfxId = 319;
pub const TSFX_PEGBOY29: SfxId = 320;
pub const TSFX_PEGBOY30: SfxId = 321;
pub const TSFX_PEGBOY31: SfxId = 322;
pub const TSFX_PEGBOY32: SfxId = 323;
pub const TSFX_PEGBOY33: SfxId = 324;
pub const TSFX_PEGBOY34: SfxId = 325;
pub const TSFX_PEGBOY35: SfxId = 326;
pub const TSFX_PEGBOY36: SfxId = 327;
pub const TSFX_PEGBOY37: SfxId = 328;
pub const TSFX_PEGBOY38: SfxId = 329;
pub const TSFX_PEGBOY39: SfxId = 330;
pub const TSFX_PEGBOY40: SfxId = 331;
pub const TSFX_PEGBOY41: SfxId = 332;
pub const TSFX_PEGBOY42: SfxId = 333;
pub const TSFX_PEGBOY43: SfxId = 334;
pub const TSFX_PRIEST0: SfxId = 335;
pub const TSFX_PRIEST1: SfxId = 336;
pub const TSFX_PRIEST2: SfxId = 337;
pub const TSFX_PRIEST3: SfxId = 338;
pub const TSFX_PRIEST4: SfxId = 339;
pub const TSFX_PRIEST5: SfxId = 340;
pub const TSFX_PRIEST6: SfxId = 341;
pub const TSFX_PRIEST7: SfxId = 342;
pub const TSFX_STORY0: SfxId = 343;
pub const TSFX_STORY1: SfxId = 344;
pub const TSFX_STORY2: SfxId = 345;
pub const TSFX_STORY3: SfxId = 346;
pub const TSFX_STORY4: SfxId = 347;
pub const TSFX_STORY5: SfxId = 348;
pub const TSFX_STORY6: SfxId = 349;
pub const TSFX_STORY7: SfxId = 350;
pub const TSFX_STORY8: SfxId = 351;
pub const TSFX_STORY9: SfxId = 352;
pub const TSFX_STORY10: SfxId = 353;
pub const TSFX_STORY11: SfxId = 354;
pub const TSFX_STORY12: SfxId = 355;
pub const TSFX_STORY13: SfxId = 356;
pub const TSFX_STORY14: SfxId = 357;
pub const TSFX_STORY15: SfxId = 358;
pub const TSFX_STORY16: SfxId = 359;
pub const TSFX_STORY17: SfxId = 360;
pub const TSFX_STORY18: SfxId = 361;
pub const TSFX_STORY19: SfxId = 362;
pub const TSFX_STORY20: SfxId = 363;
pub const TSFX_STORY21: SfxId = 364;
pub const TSFX_STORY22: SfxId = 365;
pub const TSFX_STORY23: SfxId = 366;
pub const TSFX_STORY24: SfxId = 367;
pub const TSFX_STORY25: SfxId = 368;
pub const TSFX_STORY26: SfxId = 369;
pub const TSFX_STORY27: SfxId = 370;
pub const TSFX_STORY28: SfxId = 371;
pub const TSFX_STORY29: SfxId = 372;
pub const TSFX_STORY30: SfxId = 373;
pub const TSFX_STORY31: SfxId = 374;
pub const TSFX_STORY32: SfxId = 375;
pub const TSFX_STORY33: SfxId = 376;
pub const TSFX_STORY34: SfxId = 377;
pub const TSFX_STORY35: SfxId = 378;
pub const TSFX_STORY36: SfxId = 379;
pub const TSFX_STORY37: SfxId = 380;
pub const TSFX_STORY38: SfxId = 381;
pub const TSFX_TAVERN0: SfxId = 382;
pub const TSFX_TAVERN1: SfxId = 383;
pub const TSFX_TAVERN2: SfxId = 384;
pub const TSFX_TAVERN3: SfxId = 385;
pub const TSFX_TAVERN4: SfxId = 386;
pub const TSFX_TAVERN5: SfxId = 387;
pub const TSFX_TAVERN6: SfxId = 388;
pub const TSFX_TAVERN7: SfxId = 389;
pub const TSFX_TAVERN8: SfxId = 390;
pub const TSFX_TAVERN9: SfxId = 391;
pub const TSFX_TAVERN10: SfxId = 392;
pub const TSFX_TAVERN11: SfxId = 393;
pub const TSFX_TAVERN12: SfxId = 394;
pub const TSFX_TAVERN13: SfxId = 395;
pub const TSFX_TAVERN14: SfxId = 396;
pub const TSFX_TAVERN15: SfxId = 397;
pub const TSFX_TAVERN16: SfxId = 398;
pub const TSFX_TAVERN17: SfxId = 399;
pub const TSFX_TAVERN18: SfxId = 400;
pub const TSFX_TAVERN19: SfxId = 401;
pub const TSFX_TAVERN20: SfxId = 402;
pub const TSFX_TAVERN21: SfxId = 403;
pub const TSFX_TAVERN22: SfxId = 404;
pub const TSFX_TAVERN23: SfxId = 405;
pub const TSFX_TAVERN24: SfxId = 406;
pub const TSFX_TAVERN25: SfxId = 407;
pub const TSFX_TAVERN26: SfxId = 408;
pub const TSFX_TAVERN27: SfxId = 409;
pub const TSFX_TAVERN28: SfxId = 410;
pub const TSFX_TAVERN29: SfxId = 411;
pub const TSFX_TAVERN30: SfxId = 412;
pub const TSFX_TAVERN31: SfxId = 413;
pub const TSFX_TAVERN32: SfxId = 414;
pub const TSFX_TAVERN33: SfxId = 415;
pub const TSFX_TAVERN34: SfxId = 416;
pub const TSFX_TAVERN35: SfxId = 417;
pub const TSFX_TAVERN36: SfxId = 418;
pub const TSFX_TAVERN37: SfxId = 419;
pub const TSFX_TAVERN38: SfxId = 420;
pub const TSFX_TAVERN39: SfxId = 421;
pub const TSFX_TAVERN40: SfxId = 422;
pub const TSFX_TAVERN41: SfxId = 423;
pub const TSFX_TAVERN42: SfxId = 424;
pub const TSFX_TAVERN43: SfxId = 425;
pub const TSFX_TAVERN44: SfxId = 426;
pub const TSFX_TAVERN45: SfxId = 427;
pub const TSFX_WITCH1: SfxId = 428;
pub const TSFX_WITCH2: SfxId = 429;
pub const TSFX_WITCH3: SfxId = 430;
pub const TSFX_WITCH4: SfxId = 431;
pub const TSFX_WITCH5: SfxId = 432;
pub const TSFX_WITCH6: SfxId = 433;
pub const TSFX_WITCH7: SfxId = 434;
pub const TSFX_WITCH8: SfxId = 435;
pub const TSFX_WITCH9: SfxId = 436;
pub const TSFX_WITCH10: SfxId = 437;
pub const TSFX_WITCH11: SfxId = 438;
pub const TSFX_WITCH12: SfxId = 439;
pub const TSFX_WITCH13: SfxId = 440;
pub const TSFX_WITCH14: SfxId = 441;
pub const TSFX_WITCH15: SfxId = 442;
pub const TSFX_WITCH16: SfxId = 443;
pub const TSFX_WITCH17: SfxId = 444;
pub const TSFX_WITCH18: SfxId = 445;
pub const TSFX_WITCH19: SfxId = 446;
pub const TSFX_WITCH20: SfxId = 447;
pub const TSFX_WITCH21: SfxId = 448;
pub const TSFX_WITCH22: SfxId = 449;
pub const TSFX_WITCH23: SfxId = 450;
pub const TSFX_WITCH24: SfxId = 451;
pub const TSFX_WITCH25: SfxId = 452;
pub const TSFX_WITCH26: SfxId = 453;
pub const TSFX_WITCH27: SfxId = 454;
pub const TSFX_WITCH28: SfxId = 455;
pub const TSFX_WITCH29: SfxId = 456;
pub const TSFX_WITCH30: SfxId = 457;
pub const TSFX_WITCH31: SfxId = 458;
pub const TSFX_WITCH32: SfxId = 459;
pub const TSFX_WITCH33: SfxId = 460;
pub const TSFX_WITCH34: SfxId = 461;
pub const TSFX_WITCH35: SfxId = 462;
pub const TSFX_WITCH36: SfxId = 463;
pub const TSFX_WITCH37: SfxId = 464;
pub const TSFX_WITCH38: SfxId = 465;
pub const TSFX_WITCH39: SfxId = 466;
pub const TSFX_WITCH40: SfxId = 467;
pub const TSFX_WITCH41: SfxId = 468;
pub const TSFX_WITCH42: SfxId = 469;
pub const TSFX_WITCH43: SfxId = 470;
pub const TSFX_WITCH44: SfxId = 471;
pub const TSFX_WITCH45: SfxId = 472;
pub const TSFX_WITCH46: SfxId = 473;
pub const TSFX_WITCH47: SfxId = 474;
pub const TSFX_WITCH48: SfxId = 475;
pub const TSFX_WITCH49: SfxId = 476;
pub const TSFX_WITCH50: SfxId = 477;
pub const TSFX_WOUND: SfxId = 478;
pub const PS_MAGE1: SfxId = 479;
pub const PS_MAGE2: SfxId = 480;
pub const PS_MAGE3: SfxId = 481;
pub const PS_MAGE4: SfxId = 482;
pub const PS_MAGE5: SfxId = 483;
pub const PS_MAGE6: SfxId = 484;
pub const PS_MAGE7: SfxId = 485;
pub const PS_MAGE8: SfxId = 486;
pub const PS_MAGE9: SfxId = 487;
pub const PS_MAGE10: SfxId = 488;
pub const PS_MAGE11: SfxId = 489;
pub const PS_MAGE12: SfxId = 490;
pub const PS_MAGE13: SfxId = 491;
pub const PS_MAGE14: SfxId = 492;
pub const PS_MAGE15: SfxId = 493;
pub const PS_MAGE16: SfxId = 494;
pub const PS_MAGE17: SfxId = 495;
pub const PS_MAGE18: SfxId = 496;
pub const PS_MAGE19: SfxId = 497;
pub const PS_MAGE20: SfxId = 498;
pub const PS_MAGE21: SfxId = 499;
pub const PS_MAGE22: SfxId = 500;
pub const PS_MAGE23: SfxId = 501;
pub const PS_MAGE24: SfxId = 502;
pub const PS_MAGE25: SfxId = 503;
pub const PS_MAGE26: SfxId = 504;
pub const PS_MAGE27: SfxId = 505;
pub const PS_MAGE28: SfxId = 506;
pub const PS_MAGE29: SfxId = 507;
pub const PS_MAGE30: SfxId = 508;
pub const PS_MAGE31: SfxId = 509;
pub const PS_MAGE32: SfxId = 510;
pub const PS_MAGE33: SfxId = 511;
pub const PS_MAGE34: SfxId = 512;
pub const PS_MAGE35: SfxId = 513;
pub const PS_MAGE36: SfxId = 514;
pub const PS_MAGE37: SfxId = 515;
pub const PS_MAGE38: SfxId = 516;
pub const PS_MAGE39: SfxId = 517;
pub const PS_MAGE40: SfxId = 518;
pub const PS_MAGE41: SfxId = 519;
pub const PS_MAGE42: SfxId = 520;
pub const PS_MAGE43: SfxId = 521;
pub const PS_MAGE44: SfxId = 522;
pub const PS_MAGE45: SfxId = 523;
pub const PS_MAGE46: SfxId = 524;
pub const PS_MAGE47: SfxId = 525;
pub const PS_MAGE48: SfxId = 526;
pub const PS_MAGE49: SfxId = 527;
pub const PS_MAGE50: SfxId = 528;
pub const PS_MAGE51: SfxId = 529;
pub const PS_MAGE52: SfxId = 530;
pub const PS_MAGE53: SfxId = 531;
pub const PS_MAGE54: SfxId = 532;
pub const PS_MAGE55: SfxId = 533;
pub const PS_MAGE56: SfxId = 534;
pub const PS_MAGE57: SfxId = 535;
pub const PS_MAGE58: SfxId = 536;
pub const PS_MAGE59: SfxId = 537;
pub const PS_MAGE60: SfxId = 538;
pub const PS_MAGE61: SfxId = 539;
pub const PS_MAGE62: SfxId = 540;
pub const PS_MAGE63: SfxId = 541;
pub const PS_MAGE64: SfxId = 542;
pub const PS_MAGE65: SfxId = 543;
pub const PS_MAGE66: SfxId = 544;
pub const PS_MAGE67: SfxId = 545;
pub const PS_MAGE68: SfxId = 546;
pub const PS_MAGE69: SfxId = 547;
pub const PS_MAGE69B: SfxId = 548;
pub const PS_MAGE70: SfxId = 549;
pub const PS_MAGE71: SfxId = 550;
pub const PS_MAGE72: SfxId = 551;
pub const PS_MAGE73: SfxId = 552;
pub const PS_MAGE74: SfxId = 553;
pub const PS_MAGE75: SfxId = 554;
pub const PS_MAGE76: SfxId = 555;
pub const PS_MAGE77: SfxId = 556;
pub const PS_MAGE78: SfxId = 557;
pub const PS_MAGE79: SfxId = 558;
pub const PS_MAGE80: SfxId = 559;
pub const PS_MAGE81: SfxId = 560;
pub const PS_MAGE82: SfxId = 561;
pub const PS_MAGE83: SfxId = 562;
pub const PS_MAGE84: SfxId = 563;
pub const PS_MAGE85: SfxId = 564;
pub const PS_MAGE86: SfxId = 565;
pub const PS_MAGE87: SfxId = 566;
pub const PS_MAGE88: SfxId = 567;
pub const PS_MAGE89: SfxId = 568;
pub const PS_MAGE90: SfxId = 569;
pub const PS_MAGE91: SfxId = 570;
pub const PS_MAGE92: SfxId = 571;
pub const PS_MAGE93: SfxId = 572;
pub const PS_MAGE94: SfxId = 573;
pub const PS_MAGE95: SfxId = 574;
pub const PS_MAGE96: SfxId = 575;
pub const PS_MAGE97: SfxId = 576;
pub const PS_MAGE98: SfxId = 577;
pub const PS_MAGE99: SfxId = 578;
pub const PS_MAGE100: SfxId = 579;
pub const PS_MAGE101: SfxId = 580;
pub const PS_MAGE102: SfxId = 581;
pub const PS_ROGUE1: SfxId = 582;
pub const PS_ROGUE2: SfxId = 583;
pub const PS_ROGUE3: SfxId = 584;
pub const PS_ROGUE4: SfxId = 585;
pub const PS_ROGUE5: SfxId = 586;
pub const PS_ROGUE6: SfxId = 587;
pub const PS_ROGUE7: SfxId = 588;
pub const PS_ROGUE8: SfxId = 589;
pub const PS_ROGUE9: SfxId = 590;
pub const PS_ROGUE10: SfxId = 591;
pub const PS_ROGUE11: SfxId = 592;
pub const PS_ROGUE12: SfxId = 593;
pub const PS_ROGUE13: SfxId = 594;
pub const PS_ROGUE14: SfxId = 595;
pub const PS_ROGUE15: SfxId = 596;
pub const PS_ROGUE16: SfxId = 597;
pub const PS_ROGUE17: SfxId = 598;
pub const PS_ROGUE18: SfxId = 599;
pub const PS_ROGUE19: SfxId = 600;
pub const PS_ROGUE20: SfxId = 601;
pub const PS_ROGUE21: SfxId = 602;
pub const PS_ROGUE22: SfxId = 603;
pub const PS_ROGUE23: SfxId = 604;
pub const PS_ROGUE24: SfxId = 605;
pub const PS_ROGUE25: SfxId = 606;
pub const PS_ROGUE26: SfxId = 607;
pub const PS_ROGUE27: SfxId = 608;
pub const PS_ROGUE28: SfxId = 609;
pub const PS_ROGUE29: SfxId = 610;
pub const PS_ROGUE30: SfxId = 611;
pub const PS_ROGUE31: SfxId = 612;
pub const PS_ROGUE32: SfxId = 613;
pub const PS_ROGUE33: SfxId = 614;
pub const PS_ROGUE34: SfxId = 615;
pub const PS_ROGUE35: SfxId = 616;
pub const PS_ROGUE36: SfxId = 617;
pub const PS_ROGUE37: SfxId = 618;
pub const PS_ROGUE38: SfxId = 619;
pub const PS_ROGUE39: SfxId = 620;
pub const PS_ROGUE40: SfxId = 621;
pub const PS_ROGUE41: SfxId = 622;
pub const PS_ROGUE42: SfxId = 623;
pub const PS_ROGUE43: SfxId = 624;
pub const PS_ROGUE44: SfxId = 625;
pub const PS_ROGUE45: SfxId = 626;
pub const PS_ROGUE46: SfxId = 627;
pub const PS_ROGUE47: SfxId = 628;
pub const PS_ROGUE48: SfxId = 629;
pub const PS_ROGUE49: SfxId = 630;
pub const PS_ROGUE50: SfxId = 631;
pub const PS_ROGUE51: SfxId = 632;
pub const PS_ROGUE52: SfxId = 633;
pub const PS_ROGUE53: SfxId = 634;
pub const PS_ROGUE54: SfxId = 635;
pub const PS_ROGUE55: SfxId = 636;
pub const PS_ROGUE56: SfxId = 637;
pub const PS_ROGUE57: SfxId = 638;
pub const PS_ROGUE58: SfxId = 639;
pub const PS_ROGUE59: SfxId = 640;
pub const PS_ROGUE60: SfxId = 641;
pub const PS_ROGUE61: SfxId = 642;
pub const PS_ROGUE62: SfxId = 643;
pub const PS_ROGUE63: SfxId = 644;
pub const PS_ROGUE64: SfxId = 645;
pub const PS_ROGUE65: SfxId = 646;
pub const PS_ROGUE66: SfxId = 647;
pub const PS_ROGUE67: SfxId = 648;
pub const PS_ROGUE68: SfxId = 649;
pub const PS_ROGUE69: SfxId = 650;
pub const PS_ROGUE69B: SfxId = 651;
pub const PS_ROGUE70: SfxId = 652;
pub const PS_ROGUE71: SfxId = 653;
pub const PS_ROGUE72: SfxId = 654;
pub const PS_ROGUE73: SfxId = 655;
pub const PS_ROGUE74: SfxId = 656;
pub const PS_ROGUE75: SfxId = 657;
pub const PS_ROGUE76: SfxId = 658;
pub const PS_ROGUE77: SfxId = 659;
pub const PS_ROGUE78: SfxId = 660;
pub const PS_ROGUE79: SfxId = 661;
pub const PS_ROGUE80: SfxId = 662;
pub const PS_ROGUE81: SfxId = 663;
pub const PS_ROGUE82: SfxId = 664;
pub const PS_ROGUE83: SfxId = 665;
pub const PS_ROGUE84: SfxId = 666;
pub const PS_ROGUE85: SfxId = 667;
pub const PS_ROGUE86: SfxId = 668;
pub const PS_ROGUE87: SfxId = 669;
pub const PS_ROGUE88: SfxId = 670;
pub const PS_ROGUE89: SfxId = 671;
pub const PS_ROGUE90: SfxId = 672;
pub const PS_ROGUE91: SfxId = 673;
pub const PS_ROGUE92: SfxId = 674;
pub const PS_ROGUE93: SfxId = 675;
pub const PS_ROGUE94: SfxId = 676;
pub const PS_ROGUE95: SfxId = 677;
pub const PS_ROGUE96: SfxId = 678;
pub const PS_ROGUE97: SfxId = 679;
pub const PS_ROGUE98: SfxId = 680;
pub const PS_ROGUE99: SfxId = 681;
pub const PS_ROGUE100: SfxId = 682;
pub const PS_ROGUE101: SfxId = 683;
pub const PS_ROGUE102: SfxId = 684;
pub const PS_WARR1: SfxId = 685;
pub const PS_WARR2: SfxId = 686;
pub const PS_WARR3: SfxId = 687;
pub const PS_WARR4: SfxId = 688;
pub const PS_WARR5: SfxId = 689;
pub const PS_WARR6: SfxId = 690;
pub const PS_WARR7: SfxId = 691;
pub const PS_WARR8: SfxId = 692;
pub const PS_WARR9: SfxId = 693;
pub const PS_WARR10: SfxId = 694;
pub const PS_WARR11: SfxId = 695;
pub const PS_WARR12: SfxId = 696;
pub const PS_WARR13: SfxId = 697;
pub const PS_WARR14: SfxId = 698;
pub const PS_WARR14B: SfxId = 699;
pub const PS_WARR14C: SfxId = 700;
pub const PS_WARR15: SfxId = 701;
pub const PS_WARR15B: SfxId = 702;
pub const PS_WARR15C: SfxId = 703;
pub const PS_WARR16: SfxId = 704;
pub const PS_WARR16B: SfxId = 705;
pub const PS_WARR16C: SfxId = 706;
pub const PS_WARR17: SfxId = 707;
pub const PS_WARR18: SfxId = 708;
pub const PS_WARR19: SfxId = 709;
pub const PS_WARR20: SfxId = 710;
pub const PS_WARR21: SfxId = 711;
pub const PS_WARR22: SfxId = 712;
pub const PS_WARR23: SfxId = 713;
pub const PS_WARR24: SfxId = 714;
pub const PS_WARR25: SfxId = 715;
pub const PS_WARR26: SfxId = 716;
pub const PS_WARR27: SfxId = 717;
pub const PS_WARR28: SfxId = 718;
pub const PS_WARR29: SfxId = 719;
pub const PS_WARR30: SfxId = 720;
pub const PS_WARR31: SfxId = 721;
pub const PS_WARR32: SfxId = 722;
pub const PS_WARR33: SfxId = 723;
pub const PS_WARR34: SfxId = 724;
pub const PS_WARR35: SfxId = 725;
pub const PS_WARR36: SfxId = 726;
pub const PS_WARR37: SfxId = 727;
pub const PS_WARR38: SfxId = 728;
pub const PS_WARR39: SfxId = 729;
pub const PS_WARR40: SfxId = 730;
pub const PS_WARR41: SfxId = 731;
pub const PS_WARR42: SfxId = 732;
pub const PS_WARR43: SfxId = 733;
pub const PS_WARR44: SfxId = 734;
pub const PS_WARR45: SfxId = 735;
pub const PS_WARR46: SfxId = 736;
pub const PS_WARR47: SfxId = 737;
pub const PS_WARR48: SfxId = 738;
pub const PS_WARR49: SfxId = 739;
pub const PS_WARR50: SfxId = 740;
pub const PS_WARR51: SfxId = 741;
pub const PS_WARR52: SfxId = 742;
pub const PS_WARR53: SfxId = 743;
pub const PS_WARR54: SfxId = 744;
pub const PS_WARR55: SfxId = 745;
pub const PS_WARR56: SfxId = 746;
pub const PS_WARR57: SfxId = 747;
pub const PS_WARR58: SfxId = 748;
pub const PS_WARR59: SfxId = 749;
pub const PS_WARR60: SfxId = 750;
pub const PS_WARR61: SfxId = 751;
pub const PS_WARR62: SfxId = 752;
pub const PS_WARR63: SfxId = 753;
pub const PS_WARR64: SfxId = 754;
pub const PS_WARR65: SfxId = 755;
pub const PS_WARR66: SfxId = 756;
pub const PS_WARR67: SfxId = 757;
pub const PS_WARR68: SfxId = 758;
pub const PS_WARR69: SfxId = 759;
pub const PS_WARR69B: SfxId = 760;
pub const PS_WARR70: SfxId = 761;
pub const PS_WARR71: SfxId = 762;
pub const PS_WARR72: SfxId = 763;
pub const PS_WARR73: SfxId = 764;
pub const PS_WARR74: SfxId = 765;
pub const PS_WARR75: SfxId = 766;
pub const PS_WARR76: SfxId = 767;
pub const PS_WARR77: SfxId = 768;
pub const PS_WARR78: SfxId = 769;
pub const PS_WARR79: SfxId = 770;
pub const PS_WARR80: SfxId = 771;
pub const PS_WARR81: SfxId = 772;
pub const PS_WARR82: SfxId = 773;
pub const PS_WARR83: SfxId = 774;
pub const PS_WARR84: SfxId = 775;
pub const PS_WARR85: SfxId = 776;
pub const PS_WARR86: SfxId = 777;
pub const PS_WARR87: SfxId = 778;
pub const PS_WARR88: SfxId = 779;
pub const PS_WARR89: SfxId = 780;
pub const PS_WARR90: SfxId = 781;
pub const PS_WARR91: SfxId = 782;
pub const PS_WARR92: SfxId = 783;
pub const PS_WARR93: SfxId = 784;
pub const PS_WARR94: SfxId = 785;
pub const PS_WARR95: SfxId = 786;
pub const PS_WARR95B: SfxId = 787;
pub const PS_WARR95C: SfxId = 788;
pub const PS_WARR95D: SfxId = 789;
pub const PS_WARR95E: SfxId = 790;
pub const PS_WARR95F: SfxId = 791;
pub const PS_WARR96B: SfxId = 792;
pub const PS_WARR97: SfxId = 793;
pub const PS_WARR98: SfxId = 794;
pub const PS_WARR99: SfxId = 795;
pub const PS_WARR100: SfxId = 796;
pub const PS_WARR101: SfxId = 797;
pub const PS_WARR102: SfxId = 798;
pub const PS_MONK1: SfxId = 799;
pub const PS_MONK8: SfxId = 800;
pub const PS_MONK9: SfxId = 801;
pub const PS_MONK10: SfxId = 802;
pub const PS_MONK11: SfxId = 803;
pub const PS_MONK12: SfxId = 804;
pub const PS_MONK13: SfxId = 805;
pub const PS_MONK14: SfxId = 806;
pub const PS_MONK15: SfxId = 807;
pub const PS_MONK16: SfxId = 808;
pub const PS_MONK24: SfxId = 809;
pub const PS_MONK27: SfxId = 810;
pub const PS_MONK29: SfxId = 811;
pub const PS_MONK34: SfxId = 812;
pub const PS_MONK35: SfxId = 813;
pub const PS_MONK43: SfxId = 814;
pub const PS_MONK46: SfxId = 815;
pub const PS_MONK49: SfxId = 816;
pub const PS_MONK50: SfxId = 817;
pub const PS_MONK52: SfxId = 818;
pub const PS_MONK54: SfxId = 819;
pub const PS_MONK55: SfxId = 820;
pub const PS_MONK56: SfxId = 821;
pub const PS_MONK61: SfxId = 822;
pub const PS_MONK62: SfxId = 823;
pub const PS_MONK68: SfxId = 824;
pub const PS_MONK69: SfxId = 825;
pub const PS_MONK69B: SfxId = 826;
pub const PS_MONK70: SfxId = 827;
pub const PS_MONK71: SfxId = 828;
pub const PS_MONK79: SfxId = 829;
pub const PS_MONK80: SfxId = 830;
pub const PS_MONK82: SfxId = 831;
pub const PS_MONK83: SfxId = 832;
pub const PS_MONK87: SfxId = 833;
pub const PS_MONK88: SfxId = 834;
pub const PS_MONK89: SfxId = 835;
pub const PS_MONK91: SfxId = 836;
pub const PS_MONK92: SfxId = 837;
pub const PS_MONK94: SfxId = 838;
pub const PS_MONK95: SfxId = 839;
pub const PS_MONK96: SfxId = 840;
pub const PS_MONK97: SfxId = 841;
pub const PS_MONK98: SfxId = 842;
pub const PS_MONK99: SfxId = 843;
pub const PS_NAR1: SfxId = 844;
pub const PS_NAR2: SfxId = 845;
pub const PS_NAR3: SfxId = 846;
pub const PS_NAR4: SfxId = 847;
pub const PS_NAR5: SfxId = 848;
pub const PS_NAR6: SfxId = 849;
pub const PS_NAR7: SfxId = 850;
pub const PS_NAR8: SfxId = 851;
pub const PS_NAR9: SfxId = 852;
pub const PS_DIABLVLINT: SfxId = 853;
pub const USFX_CLEAVER: SfxId = 854;
pub const USFX_GARBUD1: SfxId = 855;
pub const USFX_GARBUD2: SfxId = 856;
pub const USFX_GARBUD3: SfxId = 857;
pub const USFX_GARBUD4: SfxId = 858;
pub const USFX_IZUAL1: SfxId = 859;
pub const USFX_LACH1: SfxId = 860;
pub const USFX_LACH2: SfxId = 861;
pub const USFX_LACH3: SfxId = 862;
pub const USFX_LAZ1: SfxId = 863;
pub const USFX_LAZ2: SfxId = 864;
pub const USFX_SKING1: SfxId = 865;
pub const USFX_SNOT1: SfxId = 866;
pub const USFX_SNOT2: SfxId = 867;
pub const USFX_SNOT3: SfxId = 868;
pub const USFX_WARLRD1: SfxId = 869;
pub const USFX_WLOCK1: SfxId = 870;
pub const USFX_ZHAR1: SfxId = 871;
pub const USFX_ZHAR2: SfxId = 872;
pub const USFX_DIABLOD: SfxId = 873;
pub const TSFX_FARMER1: SfxId = 874;
pub const TSFX_FARMER2: SfxId = 875;
pub const TSFX_FARMER2A: SfxId = 876;
pub const TSFX_FARMER3: SfxId = 877;
pub const TSFX_FARMER4: SfxId = 878;
pub const TSFX_FARMER5: SfxId = 879;
pub const TSFX_FARMER6: SfxId = 880;
pub const TSFX_FARMER7: SfxId = 881;
pub const TSFX_FARMER8: SfxId = 882;
pub const TSFX_FARMER9: SfxId = 883;
pub const TSFX_TEDDYBR1: SfxId = 884;
pub const TSFX_TEDDYBR2: SfxId = 885;
pub const TSFX_TEDDYBR3: SfxId = 886;
pub const TSFX_TEDDYBR4: SfxId = 887;
pub const USFX_DEFILER1: SfxId = 888;
pub const USFX_DEFILER2: SfxId = 889;
pub const USFX_DEFILER3: SfxId = 890;
pub const USFX_DEFILER4: SfxId = 891;
pub const USFX_DEFILER8: SfxId = 892;
pub const USFX_DEFILER6: SfxId = 893;
pub const USFX_DEFILER7: SfxId = 894;
pub const USFX_NAKRUL1: SfxId = 895;
pub const USFX_NAKRUL2: SfxId = 896;
pub const USFX_NAKRUL3: SfxId = 897;
pub const USFX_NAKRUL4: SfxId = 898;
pub const USFX_NAKRUL5: SfxId = 899;
pub const USFX_NAKRUL6: SfxId = 900;
pub const PS_NARATR3: SfxId = 901;
pub const TSFX_COWSUT1: SfxId = 902;
pub const TSFX_COWSUT2: SfxId = 903;
pub const TSFX_COWSUT3: SfxId = 904;
pub const TSFX_COWSUT4: SfxId = 905;
pub const TSFX_COWSUT4A: SfxId = 906;
pub const TSFX_COWSUT5: SfxId = 907;
pub const TSFX_COWSUT6: SfxId = 908;
pub const TSFX_COWSUT7: SfxId = 909;
pub const TSFX_COWSUT8: SfxId = 910;
pub const TSFX_COWSUT9: SfxId = 911;
pub const TSFX_COWSUT10: SfxId = 912;
pub const TSFX_COWSUT11: SfxId = 913;
pub const TSFX_COWSUT12: SfxId = 914;
pub const USFX_SKLJRN1: SfxId = 915;
pub const PS_NARATR6: SfxId = 916;
pub const PS_NARATR7: SfxId = 917;
pub const PS_NARATR8: SfxId = 918;
pub const PS_NARATR5: SfxId = 919;
pub const PS_NARATR9: SfxId = 920;
pub const PS_NARATR4: SfxId = 921;
pub const TSFX_TRADER1: SfxId = 922;
pub const IS_CROPEN: SfxId = 923;
pub const IS_CRCLOS: SfxId = 924;
pub const SFX_NONE: SfxId = -1;
pub const NUM_SFX: usize = 925;

/// `sgSFX`: (bFlags, pszName)
pub static SFX_DATA: [(u8, &str); NUM_SFX] = [
    (sfx_MISC, "sfx\\misc\\walk1.wav"),
    (sfx_MISC, "sfx\\misc\\bfire.wav"),
    (sfx_MISC, "sfx\\misc\\tmag.wav"),
    (sfx_MISC, "sfx\\misc\\swing.wav"),
    (sfx_MISC, "sfx\\misc\\swing2.wav"),
    (sfx_MISC, "sfx\\misc\\dead.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\misc\\sting1.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\misc\\fballbow.wav"),
    (sfx_STREAM, "sfx\\misc\\questdon.wav"),
    (sfx_MISC, "sfx\\items\\barlfire.wav"),
    (sfx_MISC, "sfx\\items\\barrel.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\items\\podpop8.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\items\\podpop5.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\items\\urnpop3.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\items\\urnpop2.wav"),
    (sfx_MISC, "sfx\\items\\bhit.wav"),
    (sfx_MISC, "sfx\\items\\bhit1.wav"),
    (sfx_MISC, "sfx\\items\\chest.wav"),
    (sfx_MISC, "sfx\\items\\doorclos.wav"),
    (sfx_MISC, "sfx\\items\\dooropen.wav"),
    (sfx_MISC, "sfx\\items\\flipanvl.wav"),
    (sfx_MISC, "sfx\\items\\flipaxe.wav"),
    (sfx_MISC, "sfx\\items\\flipblst.wav"),
    (sfx_MISC, "sfx\\items\\flipbody.wav"),
    (sfx_MISC, "sfx\\items\\flipbook.wav"),
    (sfx_MISC, "sfx\\items\\flipbow.wav"),
    (sfx_MISC, "sfx\\items\\flipcap.wav"),
    (sfx_MISC, "sfx\\items\\flipharm.wav"),
    (sfx_MISC, "sfx\\items\\fliplarm.wav"),
    (sfx_MISC, "sfx\\items\\flipmush.wav"),
    (sfx_MISC, "sfx\\items\\flippot.wav"),
    (sfx_MISC, "sfx\\items\\flipring.wav"),
    (sfx_MISC, "sfx\\items\\fliprock.wav"),
    (sfx_MISC, "sfx\\items\\flipscrl.wav"),
    (sfx_MISC, "sfx\\items\\flipshld.wav"),
    (sfx_MISC, "sfx\\items\\flipsign.wav"),
    (sfx_MISC, "sfx\\items\\flipstaf.wav"),
    (sfx_MISC, "sfx\\items\\flipswor.wav"),
    (sfx_MISC, "sfx\\items\\gold.wav"),
    (sfx_MISC, "sfx\\items\\invanvl.wav"),
    (sfx_MISC, "sfx\\items\\invaxe.wav"),
    (sfx_MISC, "sfx\\items\\invblst.wav"),
    (sfx_MISC, "sfx\\items\\invbody.wav"),
    (sfx_MISC, "sfx\\items\\invbook.wav"),
    (sfx_MISC, "sfx\\items\\invbow.wav"),
    (sfx_MISC, "sfx\\items\\invcap.wav"),
    (sfx_MISC, "sfx\\items\\invgrab.wav"),
    (sfx_MISC, "sfx\\items\\invharm.wav"),
    (sfx_MISC, "sfx\\items\\invlarm.wav"),
    (sfx_MISC, "sfx\\items\\invmush.wav"),
    (sfx_MISC, "sfx\\items\\invpot.wav"),
    (sfx_MISC, "sfx\\items\\invring.wav"),
    (sfx_MISC, "sfx\\items\\invrock.wav"),
    (sfx_MISC, "sfx\\items\\invscrol.wav"),
    (sfx_MISC, "sfx\\items\\invshiel.wav"),
    (sfx_MISC, "sfx\\items\\invsign.wav"),
    (sfx_MISC, "sfx\\items\\invstaf.wav"),
    (sfx_MISC, "sfx\\items\\invsword.wav"),
    (sfx_MISC, "sfx\\items\\lever.wav"),
    (sfx_MISC, "sfx\\items\\magic.wav"),
    (sfx_MISC, "sfx\\items\\magic1.wav"),
    (sfx_MISC, "sfx\\items\\readbook.wav"),
    (sfx_MISC, "sfx\\items\\sarc.wav"),
    (sfx_UI, "sfx\\items\\titlemov.wav"),
    (sfx_UI, "sfx\\items\\titlslct.wav"),
    (sfx_MISC, "sfx\\items\\trap.wav"),
    (sfx_MISC, "sfx\\misc\\cast2.wav"),
    (sfx_MISC, "sfx\\misc\\cast4.wav"),
    (sfx_MISC, "sfx\\misc\\cast6.wav"),
    (sfx_MISC, "sfx\\misc\\cast7.wav"),
    (sfx_MISC, "sfx\\misc\\cast8.wav"),
    (sfx_MISC, "sfx\\misc\\repair.wav"),
    (sfx_MISC, "sfx\\misc\\acids1.wav"),
    (sfx_MISC, "sfx\\misc\\acids2.wav"),
    (sfx_MISC, "sfx\\misc\\apoc.wav"),
    (sfx_MISC, "sfx\\misc\\blodstar.wav"),
    (sfx_MISC, "sfx\\misc\\blsimpt.wav"),
    (sfx_MISC, "sfx\\misc\\bonesp.wav"),
    (sfx_MISC, "sfx\\misc\\bsimpct.wav"),
    (sfx_MISC, "sfx\\misc\\caldron.wav"),
    (sfx_MISC, "sfx\\misc\\cbolt.wav"),
    (sfx_MISC, "sfx\\misc\\dserp.wav"),
    (sfx_MISC, "sfx\\misc\\elecimp1.wav"),
    (sfx_MISC, "sfx\\misc\\elementl.wav"),
    (sfx_MISC, "sfx\\misc\\ethereal.wav"),
    (sfx_MISC, "sfx\\misc\\fbolt1.wav"),
    (sfx_MISC, "sfx\\misc\\firimp2.wav"),
    (sfx_MISC, "sfx\\misc\\flamwave.wav"),
    (sfx_MISC, "sfx\\misc\\fountain.wav"),
    (sfx_MISC, "sfx\\misc\\golum.wav"),
    (sfx_MISC, "sfx\\misc\\gshrine.wav"),
    (sfx_MISC, "sfx\\misc\\guard.wav"),
    (sfx_MISC, "sfx\\misc\\grdlanch.wav"),
    (sfx_MISC, "sfx\\misc\\holybolt.wav"),
    (sfx_MISC, "sfx\\misc\\infravis.wav"),
    (sfx_MISC, "sfx\\misc\\invisibl.wav"),
    (sfx_MISC, "sfx\\misc\\lning1.wav"),
    (sfx_MISC, "sfx\\misc\\mshield.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\misc\\nestxpld.wav"),
    (sfx_MISC, "sfx\\misc\\nova.wav"),
    (sfx_MISC, "sfx\\misc\\puddle.wav"),
    (sfx_MISC, "sfx\\misc\\resur.wav"),
    (sfx_MISC, "sfx\\misc\\scurimp.wav"),
    (sfx_MISC, "sfx\\misc\\sentinel.wav"),
    (sfx_MISC, "sfx\\misc\\spoutstr.wav"),
    (sfx_MISC, "sfx\\misc\\trapdis.wav"),
    (sfx_MISC, "sfx\\misc\\teleport.wav"),
    (sfx_MISC, "sfx\\misc\\wallloop.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\misc\\lmag.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid01.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid02.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid03.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid04.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid05.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid06.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid07.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid08.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid09.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid10.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid11.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid12.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid13.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid14.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid15.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid16.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid17.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid18.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid19.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid20.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid21.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid22.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid23.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid24.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid25.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid26.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid27.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid28.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid29.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid30.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid31.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid32.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid33.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid34.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid35.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid36.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid37.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid38.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid39.wav"),
    (sfx_STREAM, "sfx\\towners\\bmaid40.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith01.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith02.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith03.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith04.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith05.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith06.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith07.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith08.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith09.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith10.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith11.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith12.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith13.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith14.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith15.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith16.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith17.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith18.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith19.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith20.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith21.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith22.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith23.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith24.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith25.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith26.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith27.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith28.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith29.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith30.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith31.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith32.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith33.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith34.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith35.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith36.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith37.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith38.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith39.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith40.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith41.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith42.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith43.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith44.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith45.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith46.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith47.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith48.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith49.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith50.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith51.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith52.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith53.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith54.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith55.wav"),
    (sfx_STREAM, "sfx\\towners\\bsmith56.wav"),
    (sfx_MISC, "sfx\\towners\\cow1.wav"),
    (sfx_MISC, "sfx\\towners\\cow2.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\towners\\cow7.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\towners\\cow8.wav"),
    (sfx_STREAM, "sfx\\towners\\deadguy2.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk01.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk02.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk03.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk04.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk05.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk06.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk07.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk08.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk09.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk10.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk11.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk12.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk13.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk14.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk15.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk16.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk17.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk18.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk19.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk20.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk21.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk22.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk23.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk24.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk25.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk26.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk27.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk28.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk29.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk30.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk31.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk32.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk33.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk34.wav"),
    (sfx_STREAM, "sfx\\towners\\drunk35.wav"),
    (sfx_STREAM, "sfx\\towners\\healer01.wav"),
    (sfx_STREAM, "sfx\\towners\\healer02.wav"),
    (sfx_STREAM, "sfx\\towners\\healer03.wav"),
    (sfx_STREAM, "sfx\\towners\\healer04.wav"),
    (sfx_STREAM, "sfx\\towners\\healer05.wav"),
    (sfx_STREAM, "sfx\\towners\\healer06.wav"),
    (sfx_STREAM, "sfx\\towners\\healer07.wav"),
    (sfx_STREAM, "sfx\\towners\\healer08.wav"),
    (sfx_STREAM, "sfx\\towners\\healer09.wav"),
    (sfx_STREAM, "sfx\\towners\\healer10.wav"),
    (sfx_STREAM, "sfx\\towners\\healer11.wav"),
    (sfx_STREAM, "sfx\\towners\\healer12.wav"),
    (sfx_STREAM, "sfx\\towners\\healer13.wav"),
    (sfx_STREAM, "sfx\\towners\\healer14.wav"),
    (sfx_STREAM, "sfx\\towners\\healer15.wav"),
    (sfx_STREAM, "sfx\\towners\\healer16.wav"),
    (sfx_STREAM, "sfx\\towners\\healer17.wav"),
    (sfx_STREAM, "sfx\\towners\\healer18.wav"),
    (sfx_STREAM, "sfx\\towners\\healer19.wav"),
    (sfx_STREAM, "sfx\\towners\\healer20.wav"),
    (sfx_STREAM, "sfx\\towners\\healer21.wav"),
    (sfx_STREAM, "sfx\\towners\\healer22.wav"),
    (sfx_STREAM, "sfx\\towners\\healer23.wav"),
    (sfx_STREAM, "sfx\\towners\\healer24.wav"),
    (sfx_STREAM, "sfx\\towners\\healer25.wav"),
    (sfx_STREAM, "sfx\\towners\\healer26.wav"),
    (sfx_STREAM, "sfx\\towners\\healer27.wav"),
    (sfx_STREAM, "sfx\\towners\\healer28.wav"),
    (sfx_STREAM, "sfx\\towners\\healer29.wav"),
    (sfx_STREAM, "sfx\\towners\\healer30.wav"),
    (sfx_STREAM, "sfx\\towners\\healer31.wav"),
    (sfx_STREAM, "sfx\\towners\\healer32.wav"),
    (sfx_STREAM, "sfx\\towners\\healer33.wav"),
    (sfx_STREAM, "sfx\\towners\\healer34.wav"),
    (sfx_STREAM, "sfx\\towners\\healer35.wav"),
    (sfx_STREAM, "sfx\\towners\\healer36.wav"),
    (sfx_STREAM, "sfx\\towners\\healer37.wav"),
    (sfx_STREAM, "sfx\\towners\\healer38.wav"),
    (sfx_STREAM, "sfx\\towners\\healer39.wav"),
    (sfx_STREAM, "sfx\\towners\\healer40.wav"),
    (sfx_STREAM, "sfx\\towners\\healer41.wav"),
    (sfx_STREAM, "sfx\\towners\\healer42.wav"),
    (sfx_STREAM, "sfx\\towners\\healer43.wav"),
    (sfx_STREAM, "sfx\\towners\\healer44.wav"),
    (sfx_STREAM, "sfx\\towners\\healer45.wav"),
    (sfx_STREAM, "sfx\\towners\\healer46.wav"),
    (sfx_STREAM, "sfx\\towners\\healer47.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy01.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy02.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy03.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy04.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy05.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy06.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy07.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy08.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy09.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy10.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy11.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy12.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy13.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy14.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy15.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy16.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy17.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy18.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy19.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy20.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy21.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy22.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy23.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy24.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy25.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy26.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy27.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy28.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy29.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy30.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy31.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy32.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy33.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy34.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy35.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy36.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy37.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy38.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy39.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy40.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy41.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy42.wav"),
    (sfx_STREAM, "sfx\\towners\\pegboy43.wav"),
    (sfx_STREAM, "sfx\\towners\\priest00.wav"),
    (sfx_STREAM, "sfx\\towners\\priest01.wav"),
    (sfx_STREAM, "sfx\\towners\\priest02.wav"),
    (sfx_STREAM, "sfx\\towners\\priest03.wav"),
    (sfx_STREAM, "sfx\\towners\\priest04.wav"),
    (sfx_STREAM, "sfx\\towners\\priest05.wav"),
    (sfx_STREAM, "sfx\\towners\\priest06.wav"),
    (sfx_STREAM, "sfx\\towners\\priest07.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt00.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt01.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt02.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt03.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt04.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt05.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt06.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt07.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt08.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt09.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt10.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt11.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt12.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt13.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt14.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt15.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt16.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt17.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt18.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt19.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt20.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt21.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt22.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt23.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt24.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt25.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt26.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt27.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt28.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt29.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt30.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt31.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt32.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt33.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt34.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt35.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt36.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt37.wav"),
    (sfx_STREAM, "sfx\\towners\\storyt38.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown00.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown01.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown02.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown03.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown04.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown05.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown06.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown07.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown08.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown09.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown10.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown11.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown12.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown13.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown14.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown15.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown16.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown17.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown18.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown19.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown20.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown21.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown22.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown23.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown24.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown25.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown26.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown27.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown28.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown29.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown30.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown31.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown32.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown33.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown34.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown35.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown36.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown37.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown38.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown39.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown40.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown41.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown42.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown43.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown44.wav"),
    (sfx_STREAM, "sfx\\towners\\tavown45.wav"),
    (sfx_STREAM, "sfx\\towners\\witch01.wav"),
    (sfx_STREAM, "sfx\\towners\\witch02.wav"),
    (sfx_STREAM, "sfx\\towners\\witch03.wav"),
    (sfx_STREAM, "sfx\\towners\\witch04.wav"),
    (sfx_STREAM, "sfx\\towners\\witch05.wav"),
    (sfx_STREAM, "sfx\\towners\\witch06.wav"),
    (sfx_STREAM, "sfx\\towners\\witch07.wav"),
    (sfx_STREAM, "sfx\\towners\\witch08.wav"),
    (sfx_STREAM, "sfx\\towners\\witch09.wav"),
    (sfx_STREAM, "sfx\\towners\\witch10.wav"),
    (sfx_STREAM, "sfx\\towners\\witch11.wav"),
    (sfx_STREAM, "sfx\\towners\\witch12.wav"),
    (sfx_STREAM, "sfx\\towners\\witch13.wav"),
    (sfx_STREAM, "sfx\\towners\\witch14.wav"),
    (sfx_STREAM, "sfx\\towners\\witch15.wav"),
    (sfx_STREAM, "sfx\\towners\\witch16.wav"),
    (sfx_STREAM, "sfx\\towners\\witch17.wav"),
    (sfx_STREAM, "sfx\\towners\\witch18.wav"),
    (sfx_STREAM, "sfx\\towners\\witch19.wav"),
    (sfx_STREAM, "sfx\\towners\\witch20.wav"),
    (sfx_STREAM, "sfx\\towners\\witch21.wav"),
    (sfx_STREAM, "sfx\\towners\\witch22.wav"),
    (sfx_STREAM, "sfx\\towners\\witch23.wav"),
    (sfx_STREAM, "sfx\\towners\\witch24.wav"),
    (sfx_STREAM, "sfx\\towners\\witch25.wav"),
    (sfx_STREAM, "sfx\\towners\\witch26.wav"),
    (sfx_STREAM, "sfx\\towners\\witch27.wav"),
    (sfx_STREAM, "sfx\\towners\\witch28.wav"),
    (sfx_STREAM, "sfx\\towners\\witch29.wav"),
    (sfx_STREAM, "sfx\\towners\\witch30.wav"),
    (sfx_STREAM, "sfx\\towners\\witch31.wav"),
    (sfx_STREAM, "sfx\\towners\\witch32.wav"),
    (sfx_STREAM, "sfx\\towners\\witch33.wav"),
    (sfx_STREAM, "sfx\\towners\\witch34.wav"),
    (sfx_STREAM, "sfx\\towners\\witch35.wav"),
    (sfx_STREAM, "sfx\\towners\\witch36.wav"),
    (sfx_STREAM, "sfx\\towners\\witch37.wav"),
    (sfx_STREAM, "sfx\\towners\\witch38.wav"),
    (sfx_STREAM, "sfx\\towners\\witch39.wav"),
    (sfx_STREAM, "sfx\\towners\\witch40.wav"),
    (sfx_STREAM, "sfx\\towners\\witch41.wav"),
    (sfx_STREAM, "sfx\\towners\\witch42.wav"),
    (sfx_STREAM, "sfx\\towners\\witch43.wav"),
    (sfx_STREAM, "sfx\\towners\\witch44.wav"),
    (sfx_STREAM, "sfx\\towners\\witch45.wav"),
    (sfx_STREAM, "sfx\\towners\\witch46.wav"),
    (sfx_STREAM, "sfx\\towners\\witch47.wav"),
    (sfx_STREAM, "sfx\\towners\\witch48.wav"),
    (sfx_STREAM, "sfx\\towners\\witch49.wav"),
    (sfx_STREAM, "sfx\\towners\\witch50.wav"),
    (sfx_STREAM, "sfx\\towners\\wound01.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage01.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage02.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage03.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage04.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage05.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage06.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage07.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage08.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage09.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage10.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage11.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage12.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage13.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage14.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage15.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage16.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage17.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage18.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage19.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage20.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage21.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage22.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage23.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage24.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage25.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage26.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage27.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage28.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage29.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage30.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage31.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage32.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage33.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage34.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage35.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage36.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage37.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage38.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage39.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage40.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage41.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage42.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage43.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage44.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage45.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage46.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage47.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage48.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage49.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage50.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage51.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage52.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage53.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage54.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage55.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage56.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage57.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage58.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage59.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage60.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage61.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage62.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage63.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage64.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage65.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage66.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage67.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage68.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage69.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage69b.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage70.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage71.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage72.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage73.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage74.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage75.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage76.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage77.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage78.wav"),
    (sfx_SORCERER, "sfx\\sorceror\\mage79.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage80.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage81.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage82.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage83.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage84.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage85.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage86.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage87.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage88.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage89.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage90.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage91.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage92.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage93.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage94.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage95.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage96.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage97.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage98.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage99.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage100.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage101.wav"),
    (sfx_STREAM | sfx_SORCERER, "sfx\\sorceror\\mage102.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue01.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue02.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue03.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue04.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue05.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue06.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue07.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue08.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue09.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue10.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue11.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue12.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue13.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue14.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue15.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue16.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue17.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue18.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue19.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue20.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue21.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue22.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue23.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue24.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue25.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue26.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue27.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue28.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue29.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue30.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue31.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue32.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue33.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue34.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue35.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue36.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue37.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue38.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue39.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue40.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue41.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue42.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue43.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue44.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue45.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue46.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue47.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue48.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue49.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue50.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue51.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue52.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue53.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue54.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue55.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue56.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue57.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue58.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue59.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue60.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue61.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue62.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue63.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue64.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue65.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue66.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue67.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue68.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue69.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue69b.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue70.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue71.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue72.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue73.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue74.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue75.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue76.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue77.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue78.wav"),
    (sfx_ROGUE, "sfx\\rogue\\rogue79.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue80.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue81.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue82.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue83.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue84.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue85.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue86.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue87.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue88.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue89.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue90.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue91.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue92.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue93.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue94.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue95.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue96.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue97.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue98.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue99.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue100.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue101.wav"),
    (sfx_STREAM | sfx_ROGUE, "sfx\\rogue\\rogue102.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior01.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior02.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior03.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior04.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior05.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior06.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior07.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior08.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior09.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior10.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior11.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior12.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior13.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior14.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\wario14b.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\wario14c.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior15.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\wario15b.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\wario15c.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior16.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\wario16b.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\wario16c.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior17.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior18.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior19.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior20.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior21.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior22.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior23.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior24.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior25.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior26.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior27.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior28.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior29.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior30.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior31.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior32.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior33.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior34.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior35.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior36.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior37.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior38.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior39.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior40.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior41.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior42.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior43.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior44.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior45.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior46.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior47.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior48.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior49.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior50.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior51.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior52.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior53.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior54.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior55.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior56.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior57.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior58.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior59.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior60.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior61.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior62.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior63.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior64.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior65.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior66.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior67.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior68.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior69.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\wario69b.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior70.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior71.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior72.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior73.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior74.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior75.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior76.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior77.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior78.wav"),
    (sfx_WARRIOR, "sfx\\warrior\\warior79.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior80.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior81.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior82.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior83.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior84.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior85.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior86.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior87.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior88.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior89.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior90.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior91.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior92.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior93.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior94.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior95.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario95b.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario95c.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario95d.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario95e.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario95f.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario96b.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario97.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario98.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\warior99.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario100.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario101.wav"),
    (sfx_STREAM | sfx_WARRIOR, "sfx\\warrior\\wario102.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk01.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk08.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk09.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk10.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk11.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk12.wav"),
    (sfx_MONK, "sfx\\monk\\monk13.wav"),
    (sfx_MONK, "sfx\\monk\\monk14.wav"),
    (sfx_MONK, "sfx\\monk\\monk15.wav"),
    (sfx_MONK, "sfx\\monk\\monk16.wav"),
    (sfx_MONK, "sfx\\monk\\monk24.wav"),
    (sfx_MONK, "sfx\\monk\\monk27.wav"),
    (sfx_MONK, "sfx\\monk\\monk29.wav"),
    (sfx_MONK, "sfx\\monk\\monk34.wav"),
    (sfx_MONK, "sfx\\monk\\monk35.wav"),
    (sfx_MONK, "sfx\\monk\\monk43.wav"),
    (sfx_MONK, "sfx\\monk\\monk46.wav"),
    (sfx_MONK, "sfx\\monk\\monk49.wav"),
    (sfx_MONK, "sfx\\monk\\monk50.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk52.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk54.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk55.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk56.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk61.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk62.wav"),
    (sfx_MONK, "sfx\\monk\\monk68.wav"),
    (sfx_MONK, "sfx\\monk\\monk69.wav"),
    (sfx_MONK, "sfx\\monk\\monk69b.wav"),
    (sfx_MONK, "sfx\\monk\\monk70.wav"),
    (sfx_MONK, "sfx\\monk\\monk71.wav"),
    (sfx_MONK, "sfx\\monk\\monk79.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk80.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk82.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk83.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk87.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk88.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk89.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk91.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk92.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk94.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk95.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk96.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk97.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk98.wav"),
    (sfx_STREAM | sfx_MONK, "sfx\\monk\\monk99.wav"),
    (sfx_STREAM, "sfx\\narrator\\nar01.wav"),
    (sfx_STREAM, "sfx\\narrator\\nar02.wav"),
    (sfx_STREAM, "sfx\\narrator\\nar03.wav"),
    (sfx_STREAM, "sfx\\narrator\\nar04.wav"),
    (sfx_STREAM, "sfx\\narrator\\nar05.wav"),
    (sfx_STREAM, "sfx\\narrator\\nar06.wav"),
    (sfx_STREAM, "sfx\\narrator\\nar07.wav"),
    (sfx_STREAM, "sfx\\narrator\\nar08.wav"),
    (sfx_STREAM, "sfx\\narrator\\nar09.wav"),
    (sfx_STREAM, "sfx\\misc\\lvl16int.wav"),
    (sfx_STREAM, "sfx\\monsters\\butcher.wav"),
    (sfx_STREAM, "sfx\\monsters\\garbud01.wav"),
    (sfx_STREAM, "sfx\\monsters\\garbud02.wav"),
    (sfx_STREAM, "sfx\\monsters\\garbud03.wav"),
    (sfx_STREAM, "sfx\\monsters\\garbud04.wav"),
    (sfx_STREAM, "sfx\\monsters\\izual01.wav"),
    (sfx_STREAM, "sfx\\monsters\\lach01.wav"),
    (sfx_STREAM, "sfx\\monsters\\lach02.wav"),
    (sfx_STREAM, "sfx\\monsters\\lach03.wav"),
    (sfx_STREAM, "sfx\\monsters\\laz01.wav"),
    (sfx_STREAM, "sfx\\monsters\\laz02.wav"),
    (sfx_STREAM, "sfx\\monsters\\sking01.wav"),
    (sfx_STREAM, "sfx\\monsters\\snot01.wav"),
    (sfx_STREAM, "sfx\\monsters\\snot02.wav"),
    (sfx_STREAM, "sfx\\monsters\\snot03.wav"),
    (sfx_STREAM, "sfx\\monsters\\warlrd01.wav"),
    (sfx_STREAM, "sfx\\monsters\\wlock01.wav"),
    (sfx_STREAM, "sfx\\monsters\\zhar01.wav"),
    (sfx_STREAM, "sfx\\monsters\\zhar02.wav"),
    (sfx_STREAM, "sfx\\monsters\\diablod.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer1.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer2.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer2a.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer3.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer4.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer5.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer6.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer7.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer8.wav"),
    (sfx_STREAM, "sfx\\hellfire\\farmer9.wav"),
    (sfx_STREAM, "sfx\\hellfire\\teddybr1.wav"),
    (sfx_STREAM, "sfx\\hellfire\\teddybr2.wav"),
    (sfx_STREAM, "sfx\\hellfire\\teddybr3.wav"),
    (sfx_STREAM, "sfx\\hellfire\\teddybr4.wav"),
    (sfx_STREAM, "sfx\\hellfire\\defiler1.wav"),
    (sfx_STREAM, "sfx\\hellfire\\defiler2.wav"),
    (sfx_STREAM, "sfx\\hellfire\\defiler3.wav"),
    (sfx_STREAM, "sfx\\hellfire\\defiler4.wav"),
    (sfx_STREAM, "sfx\\hellfire\\defiler8.wav"),
    (sfx_STREAM, "sfx\\hellfire\\defiler6.wav"),
    (sfx_STREAM, "sfx\\hellfire\\defiler7.wav"),
    (sfx_STREAM, "sfx\\hellfire\\nakrul1.wav"),
    (sfx_STREAM, "sfx\\hellfire\\nakrul2.wav"),
    (sfx_STREAM, "sfx\\hellfire\\nakrul3.wav"),
    (sfx_STREAM, "sfx\\hellfire\\nakrul4.wav"),
    (sfx_STREAM, "sfx\\hellfire\\nakrul5.wav"),
    (sfx_STREAM, "sfx\\hellfire\\nakrul6.wav"),
    (sfx_STREAM, "sfx\\hellfire\\naratr3.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut1.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut2.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut3.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut4.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut4a.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut5.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut6.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut7.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut8.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut9.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut10.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut11.wav"),
    (sfx_STREAM, "sfx\\hellfire\\cowsut12.wav"),
    (sfx_STREAM, "sfx\\hellfire\\skljrn1.wav"),
    (sfx_STREAM, "sfx\\hellfire\\naratr6.wav"),
    (sfx_STREAM, "sfx\\hellfire\\naratr7.wav"),
    (sfx_STREAM, "sfx\\hellfire\\naratr8.wav"),
    (sfx_STREAM, "sfx\\hellfire\\naratr5.wav"),
    (sfx_STREAM, "sfx\\hellfire\\naratr9.wav"),
    (sfx_STREAM, "sfx\\hellfire\\naratr4.wav"),
    (sfx_STREAM, "sfx\\hellfire\\trader1.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\items\\cropen.wav"),
    (sfx_MISC | sfx_HELLFIRE, "sfx\\items\\crclos.wav"),
];
